import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';

test('catalog monitoring uses marketplace cards with field-level diffs, historical listing prices and persistent read state',{timeout:45000},async t=>{
  const electron=createRequire(import.meta.url)('electron') as string;
  if(!existsSync(electron))return t.skip('Electron unavailable');
  await mkdir('.test-data',{recursive:true});
  const directory=await mkdtemp(path.resolve('.test-data/catalog-changes-ui-'));
  t.after(()=>rm(directory,{recursive:true,force:true,maxRetries:5,retryDelay:100}));
  const output=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React,{useState} from 'react';import {createRoot} from 'react-dom/client';
const {AppContext}=await import('./src/context'),{CatalogProvider}=await import('./src/host/catalog'),{default:Models}=await import('./plugins/provider.newapi/renderer/Models'),{DEFAULT_PREFERENCES}=await import('./shared/types'),{applyPreferencePatch}=await import('./shared/selections');
const {ToolConfigViewsProvider}=await import('./src/host/tool-config');
const {observeCatalogChanges,getCatalogChanges,writeCatalogChanges,advanceCatalogChanges,createCatalogSnapshot,CATALOG_CHANGES_EVENT}=await import('./shared/catalog-changes');
const site={id:'monitor-ui-fixture',url:'https://fixture.invalid'},status={system_name:'Fixture',quota_per_unit:500000};
const base={model_name:'gpt-6-pro',vendor:'OpenAI',quota_type:0,model_ratio:1,model_price:0,completion_ratio:2,enable_groups:['standard','backup'],supported_endpoint_types:[],group_ratio:{standard:.75},billing_mode:'tiered_expr',billing_expr:'(len<=272000 ? p*.6+c*6+cr*.06 : p*1.2+c*12+cr*.12)*(param("service_tier")=="fast" ? 2 : 1)'};
const catalog=models=>({models,groupRatio:{standard:1,backup:.5,fast:1.5},usableGroups:{standard:'标准',backup:'备用',fast:'快速'},autoGroups:['standard'],vendors:[]});
const old=catalog([base,{...base,model_name:'claude-removed'}]);
const updated={...base,enable_groups:['standard','fast'],group_ratio:{standard:1.5},billing_expr:base.billing_expr.replace('p*.6','p*.8').replace('"fast" ? 2','"fast" ? 3')};
const next={...catalog([updated,{...base,model_name:'gemini-added'}]),groupRatio:{standard:2,backup:.5,fast:1.5}};
localStorage.clear();observeCatalogChanges(site,old,status,{detectedAt:Date.parse('2026-10-02T02:00:00Z')});const view=observeCatalogChanges(site,next,status,{detectedAt:Date.parse('2026-10-02T02:10:00Z')});
window.fixture={errors:[],read:()=>getCatalogChanges(site),legacy:()=>{const state=structuredClone(view.state);state.events=state.events.map(event=>({...event,changes:event.changes.map(({details,detailsHash,pricing,pricingHash,...change})=>change)}));writeCatalogChanges(localStorage,view.key,state);dispatchEvent(new CustomEvent(CATALOG_CHANGES_EVENT,{detail:{key:view.key}}));}};
fixture.scenario=name=>{let before={...base},after;if(name==='fast'){after={...before,billing_expr:before.billing_expr.replace('"fast" ? 2','"fast" ? 4')};}else if(name==='large'){before={...before,billing_expr:'len>272000 ? p*4+c*15+cr*.4 : p*2+c*10+cr*.2'};after={...before,billing_expr:before.billing_expr.replace('p*4','p*6')};}else if(name==='contextualTime'){before={...before,billing_expr:'len<=272000 ? p*2*(hour("Asia/Shanghai") >= 9 && hour("Asia/Shanghai") < 18 ? 2 : 1) : p*4*(hour("Asia/Shanghai") >= 9 && hour("Asia/Shanghai") < 18 ? 3 : 1)'};after={...before,billing_expr:before.billing_expr.replace('? 2 : 1','? 4 : 1')};}else if(['time','timeRemove','timeThreshold'].includes(name)){before={...before,billing_expr:'p*2*(hour("Asia/Shanghai") >= 9 && hour("Asia/Shanghai") < 18 ? 2 : 1)'};after={...before,billing_expr:name==='time' ? before.billing_expr.replace('? 2 : 1','? 3 : 1') : name==='timeRemove' ? 'p*2' : before.billing_expr.replace('< 18','< 20')};}else if(['insert','remove'].includes(name)){before={...before,billing_expr:'len<=272000 ? p*2 : p*4'};after={...before,billing_expr:'len<=128000 ? p : len<=272000 ? p*2 : p*4'};if(name==='remove')[before,after]=[after,before];}else if(['repeat','overflow'].includes(name)){before={...before,billing_expr:'p*2'};after={...before,billing_expr:'p*2*(param("service_tier")=="fast" ? '+(name==='repeat' ? '2' : '1e308')+' : 1)*(param("service_tier")=="fast" ? '+(name==='repeat' ? '3' : '1e308')+' : 1)'};}else {before={...before,billing_expr:'p*p*2'};after={...before,billing_expr:'p*p*3'};}let state=advanceCatalogChanges(advanceCatalogChanges(null,createCatalogSnapshot(catalog([before]),status),Date.parse('2026-10-02T02:00:00Z')),createCatalogSnapshot(catalog([after]),status),Date.parse('2026-10-02T02:10:00Z'));if(name==='legacyFormula')state={...state,events:state.events.map(event=>({...event,changes:event.changes.map(({pricing,pricingHash,...change})=>change)}))};if(!writeCatalogChanges(localStorage,view.key,state))throw new Error('scenario history failed to persist '+name);dispatchEvent(new CustomEvent(CATALOG_CHANGES_EVENT,{detail:{key:view.key}}));};
addEventListener('error',event=>fixture.errors.push(event.message));addEventListener('unhandledrejection',event=>fixture.errors.push(String(event.reason)));
const snapshot={siteId:site.id,siteUrl:site.url,catalog:next,status,warnings:[],loggedIn:true,fetchedAt:Date.parse('2026-10-02T02:10:00Z')};
function App(){const [preferences,setPreferences]=useState({...structuredClone(DEFAULT_PREFERENCES),sites:[site],activeSiteId:site.id}),[tools,setTools]=useState([{tool:'codex',label:'Codex'},{tool:'claude',label:'Claude Code'}]);fixture.setTools=setTools;const context={preferences,dashboard:null,bootstrap:{desktop:true,configs:[],version:'fixture'},updatePreferences:async patch=>setPreferences(current=>applyPreferencePatch(current,patch)),toast:()=>{},configureModel:()=>{}};return <main className="desktop-shell" data-theme="light" style={{display:'block',padding:20}}><AppContext.Provider value={context}><ToolConfigViewsProvider value={tools}><CatalogProvider value={{snapshot,loading:false,error:'',refresh:async()=>{}}}><Models/></CatalogProvider></ToolConfigViewsProvider></AppContext.Provider></main>;}
createRoot(document.getElementById('root')).render(<App/>);
`},bundle:true,platform:'browser',format:'esm',target:'chrome140',write:false,loader:{'.css':'empty','.svg':'text'},define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'});
  await writeFile(path.join(directory,'app.js'),output.outputFiles[0].contents);
  const css=await Promise.all(['styles.css','workbench.css','select.css','theme-tokens.css','theme.css','updates-trends.css','filters-tools-motion.css','platform-logs.css','models-market.css','components/billing.css'].map(file=>readFile(path.join('src',file),'utf8')));
  await writeFile(path.join(directory,'style.css'),css.join('\n'));
  await writeFile(path.join(directory,'index.html'),'<html><head><meta charset="utf-8"><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script type="module" src="app.js"></script></body></html>');
  await writeFile(path.join(directory,'main.cjs'),String.raw`
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path');
for(const name of ['userData','sessionData','logs','crashDumps']){const dir=path.join(__dirname,name);fs.mkdirSync(dir,{recursive:true});app.setPath(name,dir);}app.disableHardwareAcceleration();
app.whenReady().then(async()=>{
const win=new BrowserWindow({width:1200,height:800,useContentSize:true,show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});await win.loadFile(path.join(__dirname,'index.html'));
const check=async mode=>win.webContents.executeJavaScript('('+async function(mode){
  const assert=(value,label)=>{if(!value)throw new Error(label);},until=async fn=>{const end=performance.now()+6500;while(!fn()){if(performance.now()>end)throw new Error('Timeout: '+fn+' '+fixture.errors);await new Promise(resolve=>setTimeout(resolve,20));}};
  const finish=async()=>{await new Promise(resolve=>setTimeout(resolve,120));document.getAnimations().forEach(animation=>animation.finish());await new Promise(resolve=>requestAnimationFrame(resolve));};
  await until(()=>document.querySelector('.catalog-monitor-actions .button:not(:disabled)'));
  if(!document.querySelector('#stable-capture')){const style=document.createElement('style');style.id='stable-capture';style.textContent='*,*::before,*::after{animation:none!important;transition:none!important}';document.head.append(style);}
  if(!document.querySelector('.catalog-changes-modal')){document.querySelector('.catalog-monitor-actions .button').click();await until(()=>document.querySelector('.catalog-changes-modal'));}
  await finish();const modal=document.querySelector('.catalog-changes-modal'),cards=[...modal.querySelectorAll('.catalog-change-card')];
  assert(cards.length===4,'a change type was omitted');assert(modal.scrollWidth<=modal.clientWidth+1,'modal horizontal overflow');assert(modal.getBoundingClientRect().right<=innerWidth+1,'modal outside viewport');
  for(const card of cards){assert(card.scrollWidth<=card.clientWidth+1,'card horizontal overflow');assert(card.querySelector('.model-card-top .vendor-icon'),'marketplace identity missing');}
  const card=cards.find(card=>card.querySelector('h3').textContent==='gpt-6-pro');
  if(mode==='legacy'){assert(cards.every(card=>card.querySelector('.catalog-change-legacy')),'legacy prices were fabricated');assert(!modal.textContent.includes('$0.8'),'live pricing substituted for history');return {mode,cards:cards.length};}
  const input=card.querySelector('[data-change-label="≤ 272K · 普通输入价格"]');assert(input.classList.contains('is-changed'),'input has no specific highlight');assert(input.textContent.includes('$0.6') && input.textContent.includes('$0.8'),'old/new input omitted');assert(card.querySelector('[data-change-label="≤ 272K · 输出价格"]').classList.contains('is-unchanged'),'complete unchanged default output missing');
  const fast=card.querySelector('[data-change-label="请求条件 · Fast"]');assert(fast && fast.textContent.includes('×2') && fast.textContent.includes('×3'),'Fast option did not compare multipliers');assert(getComputedStyle(fast).color!=='rgba(0, 0, 0, 0)','condition invisible');
  assert(card.querySelector('[aria-label="gpt-6-pro 历史请求条件"] [aria-pressed="true"]').textContent.includes('普通'),'default request mode is not ordinary');
  assert(card.querySelector('[aria-label="gpt-6-pro 历史计费档位"] [aria-pressed="true"]').textContent.includes('≤ 272K'),'default context tier is not standard');
  const modeGroup=card.querySelector('[aria-label="gpt-6-pro 历史请求条件"]'),tierGroup=card.querySelector('[aria-label="gpt-6-pro 历史计费档位"]'),thumbOf=group=>{const active=group.querySelector('[aria-pressed="true"]'),thumb=group.querySelector('.segmented-thumb');assert(thumb,'switch thumb missing');const match=/translate\((-?[\d.]+)px,\s*(-?[\d.]+)px\)/.exec(thumb.style.transform);assert(match,'thumb has no slide position');assert(Number(match[1])===active.offsetLeft && Number(match[2])===active.offsetTop,'thumb not aligned with the pressed segment');assert(parseFloat(thumb.style.width)===active.offsetWidth && parseFloat(thumb.style.height)===active.offsetHeight,'thumb size differs from the pressed segment');return thumb.style.transform;},initialModeThumb=thumbOf(modeGroup),initialTierThumb=thumbOf(tierGroup);
  fast.click();await until(()=>card.querySelector('[data-change-label="≤ 272K · 普通输入价格"]').textContent.includes('$2.4'));assert(card.querySelector('[data-change-label="≤ 272K · 普通输入价格"]').textContent.includes('$1.2'),'Fast old price missing');assert(thumbOf(modeGroup)!==initialModeThumb,'mode thumb did not slide to the Fast segment');card.querySelector('[aria-label="gpt-6-pro 历史请求条件"] button').click();await until(()=>card.querySelector('[data-change-label="≤ 272K · 普通输入价格"]').textContent.includes('$0.8'));
  const alternate=[...card.querySelector('[aria-label="gpt-6-pro 历史计费档位"]').querySelectorAll('button')].find(button=>button.textContent.includes('> 272K'));alternate.click();await until(()=>card.querySelector('[data-change-label="> 272K · 普通输入价格"]'));assert(card.querySelector('[data-change-label="> 272K · 普通输入价格"]').textContent.includes('$1.2'),'other historical tier lost');assert(thumbOf(tierGroup)!==initialTierThumb,'tier thumb did not slide to the large-context segment');card.querySelector('[aria-label="gpt-6-pro 历史计费档位"] button').click();await until(()=>card.querySelector('[data-change-label="≤ 272K · 普通输入价格"]'));
  assert(!modal.querySelector('code,pre,.catalog-change-formula'),'a formula enters the monitor UI');
  const route=card.querySelector('[data-change-label="模型渠道「standard」倍率"]');assert(route && route.textContent.includes('×0.75') && route.textContent.includes('×1.5'),'model route missing');
  assert(cards.find(card=>card.classList.contains('catalog-change-catalog')).textContent.includes('站点范围'),'site rule not scoped');
  assert(cards.find(card=>card.classList.contains('catalog-change-added')).querySelector('[data-change-label="≤ 272K · 普通输入价格"]').textContent.includes('$0.6'),'new model historical price missing');
  const removed=cards.find(card=>card.classList.contains('catalog-change-removed'));assert(removed.querySelector('[data-change-label="≤ 272K · 普通输入价格"]').textContent.includes('$0.6'),'removed model historical price missing');assert(removed.querySelectorAll('[data-change-label="请求条件 · Fast"]').length===1,'removed model duplicates the Fast option');
  const highlight=selector=>getComputedStyle(modal.querySelector(selector+' .catalog-change-detail dt')).color;assert(highlight('.catalog-change-added')!==highlight('.catalog-change-pricing'),'added and changed rows share a color');assert(highlight('.catalog-change-removed')!==highlight('.catalog-change-pricing'),'removed and changed rows share a color');
  assert(fixture.read().pendingCount===4,'opening implicitly acknowledges history');assert(fixture.errors.length===0,'renderer errors '+fixture.errors);
  assert(document.querySelectorAll('.model-market-grid button[title="配置 Codex"]').length===2 && document.querySelectorAll('.model-market-grid button[title="配置 Claude Code"]').length===2,'active adapter shortcuts missing');
  return {mode,cards:cards.length,width:modal.clientWidth,viewport:innerWidth};
}.toString()+')('+JSON.stringify(mode)+')');
for(const [mode,size] of [['light',[1200,800]],['short',[1000,680]],['narrow',[640,680]]]){win.setContentSize(...size);console.log('CATALOG_UI '+JSON.stringify(await check(mode)));fs.writeFileSync(path.resolve('.test-data/catalog-changes-'+mode+'.png'),(await win.webContents.capturePage()).toPNG());}
win.setContentSize(1200,800);await win.webContents.executeJavaScript('document.documentElement.dataset.theme="dark";document.querySelector(".desktop-shell").dataset.theme="dark"');console.log('CATALOG_UI '+JSON.stringify(await check('dark')));fs.writeFileSync(path.resolve('.test-data/catalog-changes-dark.png'),(await win.webContents.capturePage()).toPNG());
await win.webContents.executeJavaScript('fixture.legacy()');console.log('CATALOG_UI '+JSON.stringify(await check('legacy')));fs.writeFileSync(path.resolve('.test-data/catalog-changes-legacy.png'),(await win.webContents.capturePage()).toPNG());
await win.webContents.executeJavaScript('document.querySelector(".catalog-change-event-heading .text-link").click()');await new Promise(resolve=>setTimeout(resolve,100));const read=await win.webContents.executeJavaScript('fixture.read().pendingCount');if(read!==0)throw new Error('mark read did not persist');
for(const scenario of ['fast','large','time','unknown','legacyFormula','insert','remove','timeRemove','timeThreshold','repeat','overflow','contextualTime']){
  await win.webContents.executeJavaScript('fixture.scenario('+JSON.stringify(scenario)+')');
  console.log('CATALOG_TIERS_UI '+JSON.stringify(await win.webContents.executeJavaScript('('+async function(scenario){
    const assert=(condition,label)=>{if(!condition)throw new Error(label);},until=async fn=>{const end=performance.now()+6000;while(!fn()){if(performance.now()>end)throw new Error('Timeout '+fn);await new Promise(resolve=>setTimeout(resolve,20));}};
    await until(()=>document.querySelectorAll('.catalog-change-card').length===1);await new Promise(resolve=>setTimeout(resolve,100));const card=document.querySelector('.catalog-change-card');
    assert(!card.querySelector('code,pre,details'),'monitor reveals a formula');assert(!card.textContent.includes('输入 Tokens ×') && !card.textContent.includes('p*p'),'raw or readable formula leaked');
    if(scenario==='fast'){
      const input=card.querySelector('[data-change-label="≤ 272K · 普通输入价格"]');assert(input && input.classList.contains('is-unchanged') && input.textContent.includes('$0.6'),'Fast-only change lost unchanged ordinary input');assert(card.querySelector('[data-change-label="≤ 272K · 输出价格"]').textContent.includes('$6'),'complete default output lost');
      const fast=card.querySelector('[data-change-label="请求条件 · Fast"]');assert(fast.classList.contains('has-change'),'changed Fast option not highlighted');fast.click();await until(()=>card.querySelector('.catalog-change-price-section').textContent.includes('$2.4'));assert(card.querySelector('.catalog-change-price-section').textContent.includes('$1.2'),'Fast old unit price missing');card.querySelector('[aria-label="gpt-6-pro 历史请求条件"] button').click();
    }else if(scenario==='large'){
      const group=card.querySelector('[aria-label="gpt-6-pro 历史计费档位"]'),initial=group.querySelector('[aria-pressed="true"]');assert(initial.textContent.includes('≤ 272K'),'first changed tier incorrectly became the default');assert(!initial.classList.contains('has-change'),'unchanged default tier highlighted');assert(card.querySelector('[data-change-label="≤ 272K · 普通输入价格"]').textContent.includes('$2'),'unchanged default price absent');const large=[...group.querySelectorAll('button')].find(button=>button.textContent.includes('> 272K'));assert(large.classList.contains('has-change'),'changed larger tier not highlighted');large.click();await until(()=>card.querySelector('[data-change-label="> 272K · 普通输入价格"]'));assert(card.querySelector('[data-change-label="> 272K · 普通输入价格"]').textContent.includes('$4') && card.querySelector('[data-change-label="> 272K · 普通输入价格"]').textContent.includes('$6'),'larger tier comparison missing');initial.click();
    }else if(scenario==='time'){
      const group=card.querySelector('[aria-label="gpt-6-pro 历史计费档位"]');assert(group.querySelector('[aria-pressed="true"]').textContent.includes('09:00–18:00'),'detection-time tier not default');assert(card.querySelector('.catalog-change-price-section').textContent.includes('$4') && card.querySelector('.catalog-change-price-section').textContent.includes('$6'),'detection-time old/new prices wrong');const time=card.querySelector('.catalog-change-time-rules .is-changed');assert(time && time.textContent.includes('×2') && time.textContent.includes('×3') && time.textContent.includes('→'),'time multiplier comparison lost');const offHours=[...group.querySelectorAll('button')].find(button=>button.textContent.includes('其余时段'));offHours.click();await until(()=>card.querySelector('.catalog-change-price-section').textContent.includes('$2'));assert(card.querySelector('.catalog-change-price-row').classList.contains('is-unchanged'),'unchanged off-hours falsely changed');group.querySelector('button').click();
    }else if(scenario==='insert' || scenario==='remove'){
      const group=card.querySelector('[aria-label="gpt-6-pro 历史计费档位"]'),initial=group.querySelector('[aria-pressed="true"]'),first=card.querySelector('.catalog-change-price-row');assert(group.querySelectorAll('button').length===5,'insertion/deletion hid a recorded tier');assert(initial.textContent.includes(scenario==='insert' ? '≤ 128K' : '≤ 272K'),'new default wrong');assert(first.classList.contains(scenario==='insert' ? 'is-added' : 'is-added') && first.textContent.includes(scenario==='insert' ? '$1' : '$2') && !first.textContent.includes('→'),'index shifted tier inherited unrelated old price');const removed=[...group.querySelectorAll('button')].find(button=>button.textContent.includes(scenario==='insert' ? '≤ 272K' : '≤ 128K') && button.textContent.includes('移除'));assert(removed,'old tier is not exposed as removed');removed.click();await until(()=>card.querySelector('.catalog-change-price-row').classList.contains('is-removed'));assert(card.querySelector('.catalog-change-price-row').textContent.includes(scenario==='insert' ? '$2' : '$1'),'removed tier original price missing');initial.click();
    }else if(scenario==='timeRemove'){
      const rules=[...card.querySelectorAll('.catalog-change-time-rules .catalog-change-detail')];assert(rules.length===2 && rules.every(row=>row.classList.contains('is-removed')),'removed time rules disappeared or lack removal color');assert(rules.some(row=>row.textContent.includes('09:00–18:00') && row.textContent.includes('×2')),'removed multiplier missing');
    }else if(scenario==='timeThreshold'){
      const rules=[...card.querySelectorAll('.catalog-change-time-rules .catalog-change-detail')],remaining=rules.filter(row=>row.textContent.includes('其余时段'));assert(rules.length===4 && remaining.length===2 && remaining.some(row=>row.classList.contains('is-added')) && remaining.some(row=>row.classList.contains('is-removed')),'different remaining-period conditions merged');assert(rules.some(row=>row.textContent.includes('09:00–18:00') && row.classList.contains('is-removed')) && rules.some(row=>row.textContent.includes('09:00–20:00') && row.classList.contains('is-added')),'time threshold history missing');
    }else if(scenario==='contextualTime'){
      const rules=card.querySelector('.catalog-change-time-rules');assert(rules.textContent.includes('×2') && rules.textContent.includes('×4'),'default context time coefficients wrong');const group=card.querySelector('[aria-label="gpt-6-pro 历史计费档位"]'),high=[...group.querySelectorAll('button')].find(button=>button.textContent.includes('> 272K') && button.textContent.includes('09:00–18:00'));assert(high,'high context daytime option missing');high.click();await until(()=>card.querySelector('.catalog-change-time-rules').textContent.includes('×3'));assert(!card.querySelector('.catalog-change-time-rules').textContent.includes('×4') && !card.querySelector('.catalog-change-time-rules .is-changed'),'selected context inherited low-context time coefficients');
    }else if(scenario==='repeat' || scenario==='overflow'){
      assert(card.querySelector('.catalog-change-price-section').textContent.includes('$2'),'ordinary price lost');const group=card.querySelector('[aria-label="gpt-6-pro 历史请求条件"]');assert(group.querySelectorAll('button').length===2,'repeated Fast conditions were not combined');const fast=group.querySelector('button[data-change-label]');assert(fast.textContent.includes(scenario==='repeat' ? '×6' : '未知'),'combined/unknown multiplier wrong');fast.click();await until(()=>card.querySelector('.catalog-change-price-section h4').textContent.includes('Fast'));assert(card.querySelector('.catalog-change-price-section').textContent.includes(scenario==='repeat' ? '$12' : '未知'),'effective Fast pricing wrong');
    }else assert(card.textContent.includes('未知') || card.textContent.includes('无法'),'nonlinear pricing invents a price');
    assert(fixture.errors.length===0,'renderer error '+fixture.errors);return {scenario,formulaElements:card.querySelectorAll('code,pre,details').length};
  }.toString()+')('+JSON.stringify(scenario)+')')));
  fs.writeFileSync(path.resolve('.test-data/catalog-change-tiers-'+scenario+'.png'),(await win.webContents.capturePage()).toPNG());
}
await win.webContents.executeJavaScript('fixture.setTools([{tool:"claude",label:"Claude Code"}])');await new Promise(resolve=>setTimeout(resolve,100));const shortcuts=await win.webContents.executeJavaScript('({codex:document.querySelectorAll(".model-market-grid button[title=\\"配置 Codex\\"]").length,claude:document.querySelectorAll(".model-market-grid button[title=\\"配置 Claude Code\\"]").length})');if(shortcuts.codex!==0 || shortcuts.claude!==2)throw new Error('withdrawing Codex affected the wrong shortcuts '+JSON.stringify(shortcuts));
win.destroy();app.exit(0);
}).catch(error=>{console.error(error.stack || error);app.exit(1)});
`);
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
  const child=spawn(electron,[path.join(directory,'main.cjs')],{env,windowsHide:true,stdio:['ignore','pipe','pipe'],signal:t.signal});
  let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);
  const code=await new Promise<number|null>((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});
  assert.equal(code,0,stderr+stdout);assert.equal(stdout.split('CATALOG_UI ').length-1,5);assert.equal(stdout.split('CATALOG_TIERS_UI ').length-1,12);
});
