import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {readExtensionPackage} from '../electron/extensions/packages';

test('real marketplace searches, installs, updates and uninstalls without remounting Settings',{timeout:45000},async t=>{
  let electron:string;try{electron=createRequire(import.meta.url)('electron');}catch{return t.skip('Electron unavailable');}if(!existsSync(electron))return t.skip('Electron unavailable');
  await mkdir('.test-data',{recursive:true});const directory=await mkdtemp(path.resolve('.test-data/market-ui-'));t.after(()=>rm(directory,{recursive:true,force:true,maxRetries:5,retryDelay:100}));
  const packages=await Promise.all(['extension.lumi.notes','extension.lumi.compact'].map(async id=>{const pkg=await readExtensionPackage('extensions/packages/'+id);return {manifest:pkg.manifest,sourceUrl:'https://github.com/zhaojiseng/lumi-extensions',preview:pkg.manifest.interface ? {id,css:pkg.files.get(pkg.manifest.interface.stylesheet)!.toString(),appearanceGroups:pkg.manifest.interface.appearanceGroups} : undefined};}));
  const script=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React from 'react';import {createRoot} from 'react-dom/client';import {DEFAULT_PREFERENCES} from './shared/types';import {builtinManifests} from './plugins/manifests';import {extensionStatus} from './shared/contracts/extensions';
window.fixture={errors:[],catalog:{revision:'${'1'.repeat(40)}',fetchedAt:Date.now(),plugins:${JSON.stringify(packages)},diagnostics:[]},installed:[],failRead:true,failInstall:false,storage:{note:'keep'},listeners:new Set()};
addEventListener('error',event=>fixture.errors.push(event.message));addEventListener('unhandledrejection',event=>fixture.errors.push(String(event.reason)));
const prefs=structuredClone(DEFAULT_PREFERENCES),stub=()=>()=>{},inventory=()=>({directory:'fixture',plugins:structuredClone(fixture.installed),diagnostics:[]}),statuses=()=>[...builtinManifests.map(manifest=>({manifest,state:['provider.newapi','provider.codex','surface.widget'].includes(manifest.id) ? 'disabled' : 'active'})),...fixture.installed.map(pkg=>({...extensionStatus(pkg.manifest,pkg.enabled,1),origin:'external'}))];
window.lumi={bootstrap:async()=>({preferences:prefs,desktop:true,platform:'win32',version:'fixture',configs:[],secureStorage:true}),inspectConfigs:async()=>[],listPlugins:async()=>statuses(),extensionInventory:async()=>inventory(),reloadExtensions:async()=>inventory(),extensionMarket:async()=>{if(fixture.failRead){fixture.failRead=false;throw new Error('fixture market offline');}return structuredClone(fixture.catalog);},installExtension:async input=>{if(fixture.failInstall)throw new Error('fixture install failure');if(input.revision!==fixture.catalog.revision)throw new Error('stale revision');const item=fixture.catalog.plugins.find(pkg=>pkg.manifest.id===input.id);fixture.installed=fixture.installed.filter(pkg=>pkg.manifest.id!==input.id).concat({manifest:structuredClone(item.manifest),digest:'fixture',removable:true,enabled:false});return inventory();},removeExtension:async id=>{fixture.installed=fixture.installed.filter(pkg=>pkg.manifest.id!==id);return inventory();},setPluginEnabled:async(id,enabled)=>{fixture.installed.find(pkg=>pkg.manifest.id===id).enabled=enabled;return statuses();},syncSurfaceTheme:async()=>{},onNavigate:stub,onRefresh:stub,onWidgetVisibility:stub,onUpdate:stub,onReviewUpdate:stub,onToolRuntime:stub,onConfigProgress:stub,onAppLog:stub,updateStatus:async()=>({phase:'unsupported',currentVersion:'fixture'}),appCache:async()=>({categories:[],totalBytes:0,browserBytes:0,updateBytes:0,protectedBytes:0,warnings:[],scannedAt:Date.now()}),windowControl:async()=>{},openExternal:async url=>{fixture.opened=url;}};
const {default:App}=await import('./src/App');createRoot(document.getElementById('root')).render(<App/>);`},bundle:true,platform:'browser',format:'esm',write:false,loader:{'.css':'empty','.svg':'text'},define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'});
  await writeFile(path.join(directory,'app.js'),script.outputFiles[0].contents);
  const styles=await Promise.all(['styles.css','workbench.css','select.css','theme-tokens.css','theme.css','updates-trends.css','filters-tools-motion.css','platform-logs.css','app-cache.css','host/extension-market.css'].map(file=>readFile(path.resolve('src',file),'utf8')));await writeFile(path.join(directory,'style.css'),styles.join('\n')+'\n*{animation:none!important;transition:none!important}');
  await writeFile(path.join(directory,'index.html'),'<html><head><meta charset="UTF-8"><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script type="module" src="app.js"></script></body></html>');
  await writeFile(path.join(directory,'main.cjs'),String.raw`
const {app,BrowserWindow}=require('electron'),path=require('node:path'),fs=require('node:fs');for(const name of ['userData','sessionData','logs','crashDumps']){const dir=path.join(__dirname,name);fs.mkdirSync(dir,{recursive:true});app.setPath(name,dir);}app.disableHardwareAcceleration();app.whenReady().then(async()=>{
const win=new BrowserWindow({width:1280,height:900,show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});await win.loadFile(path.join(__dirname,'index.html'));
const result=await win.webContents.executeJavaScript('('+async function(){
const check=(value,label)=>{if(!value)throw new Error(label);},until=async fn=>{const end=performance.now()+6000;while(!fn()){if(performance.now()>end)throw new Error('Market UI timeout: '+fn);await new Promise(r=>setTimeout(r,15));}};
await until(()=>document.querySelector('.settings-page') && document.querySelector('[aria-label="余额提醒阈值"]'));
const settings=document.querySelector('.settings-page'),threshold=document.querySelector('[aria-label="余额提醒阈值"]'),scroll=document.querySelector('.content-scroll');
Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(threshold,'123.4');threshold.dispatchEvent(new Event('input',{bubbles:true}));scroll.scrollTop=80;
const open=()=>[...document.querySelectorAll('.plugin-settings-overview>.section-heading button')].find(button=>button.textContent.includes('插件市场')).click();open();await until(()=>document.querySelector('.extension-market [role=alert]'));
document.querySelector('.extension-market [role=alert] button').click();await until(()=>document.querySelectorAll('.market-item').length===2);
const kinds=document.querySelectorAll('.market-kinds button');kinds[2].click();await until(()=>document.querySelectorAll('.market-item').length===1);check(document.querySelector('.market-item').textContent.includes('紧凑界面'),'Interface filter failed');kinds[0].click();
const search=document.querySelector('[aria-label="搜索插件"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(search,'便笺');search.dispatchEvent(new Event('input',{bubbles:true}));await until(()=>document.querySelectorAll('.market-item').length===1);
document.querySelector('[aria-label="查看工作台便笺详情"]').click();await until(()=>document.querySelector('.market-detail'));check(document.querySelector('.market-detail').textContent.includes('插件存储'),'Permission details missing');
fixture.failInstall=true;document.querySelector('[aria-label="安装工作台便笺"]').click();await until(()=>document.querySelector('.extension-market [role=alert]')?.textContent.includes('fixture install failure'));check(fixture.installed.length===0,'Failed install changed inventory');
fixture.failInstall=false;document.querySelector('[aria-label="安装工作台便笺"]').click();await until(()=>document.querySelector('.market-installed')?.textContent.includes('已停用'));check(fixture.installed[0].enabled===false,'Installation automatically enabled plugin');
check(document.querySelector('.settings-page')===settings && threshold.value==='123.4' && scroll.scrollTop===80,'Install reset Settings');
document.querySelector('.market-back').click();await until(()=>document.querySelector('.market-installed-filter'));document.querySelector('.market-installed-filter input').click();await until(()=>document.querySelectorAll('.market-item').length===1);
document.querySelector('.extension-market [aria-label="关闭弹窗"]').click();await until(()=>!document.querySelector('.extension-market'));document.querySelector('[aria-label="启用工作台便笺"]').click();await until(()=>fixture.installed[0].enabled===true);
fixture.catalog.plugins[0].manifest.version='2.0.0';open();await until(()=>document.querySelector('[aria-label="更新工作台便笺"]'));document.querySelector('[aria-label="更新工作台便笺"]').click();await until(()=>fixture.installed[0].manifest.version==='2.0.0' && !fixture.installed[0].enabled);
check(document.querySelector('.settings-page')===settings && threshold.value==='123.4','Update remounted Settings');
document.querySelector('[aria-label="查看工作台便笺详情"]').click();await until(()=>document.querySelector('.market-detail'));[...document.querySelectorAll('.market-detail-actions button')].find(button=>button.textContent==='卸载').click();await until(()=>document.querySelector('.market-remove-confirm'));[...document.querySelectorAll('.market-remove-confirm button')].find(button=>button.textContent==='确认卸载').click();await until(()=>fixture.installed.length===0 && !document.querySelector('[aria-label="启用工作台便笺"]'));
check(fixture.storage.note==='keep','Uninstall removed storage');check(!document.querySelector('[aria-label="启用工作台便笺"]'),'Uninstalled plugin settings retained');
document.querySelector('.market-back').click();await until(()=>document.querySelectorAll('.market-item').length===2);document.querySelector('[aria-label="安装紧凑界面"]').click();await until(()=>fixture.installed.length===1 && document.querySelector('.interface-settings').textContent.includes('紧凑界面'));
check(document.querySelector('.desktop-shell').dataset.interface==='interface.default','Installing a theme changed the active interface');
document.querySelector('[aria-label="打开官方插件仓库"]').click();check(fixture.opened==='https://github.com/zhaojiseng/lumi-extensions','Wrong official source');
check(document.querySelector('.settings-page')===settings && threshold.value==='123.4' && scroll.scrollTop===80,'Package actions lost Settings identity/draft/scroll');
check(fixture.errors.length===0,'Renderer errors '+fixture.errors);return {installed:true,updated:true,removed:true,preserved:true};
}.toString()+')()');
for(const [width,height] of [[1280,900],[1080,800],[640,800]]){
win.setSize(width,height);await win.webContents.executeJavaScript('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
await win.webContents.executeJavaScript('('+function(){const dialog=document.querySelector('.extension-market'),rect=dialog.getBoundingClientRect();if(rect.left<0 || rect.right>innerWidth || dialog.scrollWidth>dialog.clientWidth+1)throw new Error('Marketplace overflow at '+innerWidth+': '+JSON.stringify(rect));for(const node of dialog.querySelectorAll('button,input,h3')){const r=node.getBoundingClientRect();if(r.left<rect.left || r.right>rect.right+1)throw new Error('Marketplace control overflow');}}.toString()+')()');
if(process.env.LUMI_UI_REVIEW==='1'){const out=path.resolve('.cache/ui-review');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'market-'+width+'.png'),(await win.webContents.capturePage()).toPNG());}
}
console.log('MARKET_RESULT '+JSON.stringify(result));win.destroy();app.exit(0);}).catch(error=>{console.error(error.stack || error);app.exit(1);});`);
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const child=spawn(electron,[path.join(directory,'main.cjs')],{env,windowsHide:true,stdio:['ignore','pipe','pipe'],signal:t.signal});let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);
  const code=await new Promise<number|null>((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});assert.equal(code,0,stderr+stdout);assert.match(stdout,/MARKET_RESULT.*"installed":true.*"updated":true.*"removed":true.*"preserved":true/);
});
