import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';

test('plugin groups open persistent dialogs from rows and settings buttons, trap keyboard focus, expose failures and lock independent switches',{timeout:30000},async t=>{
  let electron:string;try{electron=createRequire(import.meta.url)('electron');}catch{return t.skip('Electron runtime unavailable');}if(!existsSync(electron))return t.skip('Electron runtime unavailable');
  const base=path.resolve('.test-data');await mkdir(base,{recursive:true});const root=await mkdtemp(path.join(base,'plugin-tree-'));t.after(()=>rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100}));
  const built=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React,{useState} from 'react';import {createRoot} from 'react-dom/client';
import {builtinManifests} from './plugins/manifests';import {settingsGroups} from './shared/plugin-preferences';
import {PluginSettingsSection,PluginSettingsProvider} from './src/host/plugins';import {rendererRegistry} from './src/host/renderer-registry';
import {Modal} from './src/components/ui';
window.fixture={mounts:0,sectionLoads:0,legacyMounts:0,scopedMounts:0,writes:[],errors:[]};window.addEventListener('error',event=>fixture.errors.push(event.message));window.addEventListener('unhandledrejection',event=>fixture.errors.push(String(event.reason)));
function DraftSettings(){const [draft,setDraft]=useState(()=>{fixture.mounts++;return 'draft';});return <label>插件草稿<input className="text-input" aria-label="插件草稿" value={draft} onChange={event=>setDraft(event.target.value)}/></label>;}
function LegacySettings(){useState(()=>{fixture.legacyMounts++;return '';});return <p data-legacy-settings>兼容原有插件组件</p>;}
function ScopedSettings(){useState(()=>{fixture.scopedMounts++;return '';});return <p data-scoped-settings>模型广场设置子项</p>;}
const newapi=rendererRegistry.find(item=>item.manifest.id==='provider.newapi');newapi.settings.component=undefined;newapi.settings.sections=[{id:'fixture.draft',title:'草稿设置',description:'插件声明的自身设置',component:React.lazy(async()=>{fixture.sectionLoads++;return {default:DraftSettings};})},{id:'fixture.models',title:'模型选项',view:'models',component:ScopedSettings}];
const legacy=rendererRegistry.find(item=>item.manifest.id==='provider.codex');legacy.settings.sections=[];legacy.settings.component=LegacySettings;
const external={id:'extension.fixture',version:'1.0.0',hostApiVersion:1,configurable:true,requires:[],optional:[],provides:[],settings:{title:'测试插件',description:'演示错误在折叠状态仍可见。',order:200,views:[{id:'fixture',title:'测试子项'}]}};
function Host(){
 const [statuses,setStatuses]=useState(()=>[...builtinManifests.map(manifest=>({manifest,state:'active',views:manifest.settings ? Object.fromEntries(manifest.settings.views.map(v=>[v.id,true])) : undefined})),{manifest:external,state:'failed',error:'测试错误仍应可见',origin:'external'}]),[busyId,setBusy]=useState(null),[globalOpen,setGlobalOpen]=useState(false);fixture.openGlobal=()=>setGlobalOpen(true);
 const items=settingsGroups(statuses.map(status=>status.manifest)).map(group=>({...group,status:statuses.find(status=>status.manifest.id===group.id)}));
 const setEnabled=(id,enabled)=>new Promise(resolve=>{fixture.writes.push({id,enabled});setBusy(id);setStatuses(all=>all.map(status=>status.manifest.id===id ? {...status,state:enabled ? 'activating' : 'deactivating'} : status));fixture.complete=()=>{setStatuses(all=>all.map(status=>status.manifest.id===id ? {...status,state:enabled ? 'active' : 'disabled'} : status));setBusy(null);resolve();};});
 const setView=async(id,view,enabled)=>{fixture.writes.push({id,view,enabled});setStatuses(all=>all.map(status=>status.manifest.id===id ? {...status,views:{...status.views,[view]:enabled}} : status));};
 return <PluginSettingsProvider value={{items,statuses,loading:false,busyId,error:'',setEnabled,setView,extensions:{directory:'fixture',plugins:[],diagnostics:[{package:'bad-package',error:'目录诊断错误'}]}}}><div className="content-scroll"><div className="page settings-page"><PluginSettingsSection/></div></div>{globalOpen && <Modal title="全局账户窗口" onClose={()=>setGlobalOpen(false)}><input className="text-input" aria-label="全局账户草稿" defaultValue="root modal"/></Modal>}</PluginSettingsProvider>;
}
createRoot(document.getElementById('root')).render(<Host/>);`},bundle:true,platform:'browser',format:'esm',write:false,loader:{'.css':'empty','.svg':'text'},define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'});
  await writeFile(path.join(root,'renderer.js'),built.outputFiles[0].contents);
  const css=await Promise.all(['styles.css','workbench.css','select.css','theme-tokens.css','theme.css','updates-trends.css','filters-tools-motion.css','platform-logs.css','app-cache.css'].map(file=>readFile(path.resolve('src',file),'utf8')));
  await writeFile(path.join(root,'style.css'),css.join('\n')+'\nbody{padding:24px;background:var(--background)}#root{max-width:1040px;margin:auto}.content-scroll{height:calc(100vh - 48px);overflow:auto;padding:0}.settings-page{gap:16px;padding:0 0 200px}*{animation:none!important;transition:none!important}');
  await writeFile(path.join(root,'index.html'),'<html data-theme="light"><head><meta charset="UTF-8"><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script type="module" src="renderer.js"></script></body></html>');
  await writeFile(path.join(root,'audit.cjs'),String.raw`
const {app,BrowserWindow}=require('electron'),path=require('node:path'),fs=require('node:fs');
for(const name of ['userData','sessionData','logs','crashDumps']){const directory=path.join(__dirname,name);fs.mkdirSync(directory,{recursive:true});app.setPath(name,directory);}
app.disableHardwareAcceleration();app.whenReady().then(async()=>{
 const win=new BrowserWindow({show:false,width:1120,height:900,webPreferences:{offscreen:true,sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});await win.loadFile(path.join(__dirname,'index.html'));
 const result=await win.webContents.executeJavaScript('('+async function(){
  const check=(value,message)=>{if(!value)throw new Error(message);},until=async fn=>{const end=performance.now()+4000;while(!fn()){if(performance.now()>end)throw new Error('Tree timeout: '+fn.toString());await new Promise(resolve=>setTimeout(resolve,10));}};
  await until(()=>document.querySelectorAll('.plugin-settings-group').length===7);
  const branches=Array.from(document.querySelectorAll('.plugin-branch-toggle'));check(branches.map(button=>button.querySelector('strong').textContent).join(',')==='内置插件,工具配置,额外插件','Settings branches');
  const tools=document.querySelector('[data-plugin-group=tools]'),toolNodes=Array.from(tools.querySelectorAll('.plugin-settings-group'));check(toolNodes.map(node=>node.dataset.plugin).join(',')==='adapter.tool.codex,adapter.tool.claude','Independent tools in own branch');
  const provider=document.querySelector('[data-plugin="provider.newapi"]'),row=provider.querySelector('.plugin-row-button'),overview=document.querySelector('.plugin-settings-overview'),scroll=document.querySelector('.content-scroll'),dialog=()=>Array.from(document.querySelectorAll('.plugin-details-modal')).find(element=>!element.closest('[hidden],[inert]')),close=()=>dialog().querySelector('[aria-label="关闭弹窗"]').click();
  check(!row.hasAttribute('aria-expanded') && !document.querySelector('.plugin-node-toggle'),'Leaf plugins open settings dialogs');check(fixture.mounts===0 && fixture.sectionLoads===0 && fixture.legacyMounts===0,'Own setting components stay lazy until visited');
  scroll.scrollTop=50;row.focus({preventScroll:true});row.click();await until(()=>dialog() && dialog().querySelector('[aria-label="插件草稿"]') && dialog().contains(document.activeElement));const detail=document.querySelector('[data-plugin-details="provider.newapi"]'),draft=detail.querySelector('[aria-label="插件草稿"]');check(!overview.hidden && dialog().getAttribute('aria-label')==='NewAPI 插件设置','Row opens labelled dialog while keeping the list');check(scroll.scrollTop===50,'Opening leaves list scroll unchanged');check(detail.textContent.includes('插件介绍') && detail.textContent.includes('插件自身设置') && detail.textContent.includes('显示内容'),'Detail exposes introduction, own settings and views');check(fixture.sectionLoads===1 && fixture.scopedMounts===1,'Lazy section and associated view load once');
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(draft,'未保存的插件草稿');draft.dispatchEvent(new Event('input',{bubbles:true}));await until(()=>draft.value==='未保存的插件草稿');
  close();await until(()=>!dialog());check(document.activeElement===row && scroll.scrollTop===50,'Close restores exact row focus and list scroll');const settingsButton=provider.querySelector('.plugin-settings-button');settingsButton.click();await until(()=>dialog());check(document.querySelector('[aria-label="插件草稿"]')===draft && draft.value==='未保存的插件草稿' && fixture.mounts===1,'Settings button opens same retained detail');
  const child=detail.querySelector('[aria-label="显示NewAPI 模型广场"]');child.click();await until(()=>child.getAttribute('aria-checked')==='false' && !detail.querySelector('[data-scoped-settings]'));check(draft.value==='未保存的插件草稿','Turning view off preserves unrelated own-setting draft');close();await until(()=>!dialog());check(document.activeElement===settingsButton && scroll.scrollTop===50,'Close restores exact settings button');
  branches[0].click();await until(()=>document.getElementById(branches[0].getAttribute('aria-controls')).hidden);branches[0].click();await until(()=>!document.getElementById(branches[0].getAttribute('aria-controls')).hidden);check(document.querySelector('[aria-label="插件草稿"]')===draft && fixture.mounts===1,'Parent folding retained visited mounted panel');
  const failure=()=>Array.from(document.querySelectorAll('[role=alert]')).find(element=>element.textContent.includes('测试错误仍应可见') && element.getBoundingClientRect().height>0);
  check(failure(),'Failed child visible while folded');branches[2].click();await until(()=>branches[2].getAttribute('aria-expanded')==='false');check(failure(),'Failed child visible while parent folded');check(document.querySelector('.extension-manager [role=alert]').getBoundingClientRect().height>0,'Scan diagnostics visible');
  const codex=tools.querySelector('[aria-label="启用Codex 工具配置"]'),claude=tools.querySelector('[aria-label="启用Claude Code 工具配置"]');codex.focus();codex.click();await until(()=>codex.getAttribute('aria-busy')==='true');check(codex.getAttribute('aria-disabled')==='true' && claude.getAttribute('aria-disabled')==='true','Pending locks both switches');claude.click();check(fixture.writes.length===2,'Busy switch ignores duplicate update');fixture.complete();await until(()=>codex.getAttribute('aria-disabled')==='false');check(codex.getAttribute('aria-checked')==='false' && claude.getAttribute('aria-checked')==='true','Disabling Codex leaves Claude on');check(document.activeElement===codex,'Pending switch keeps focus');
  const subscription=document.querySelector('[data-plugin="provider.codex"]');subscription.querySelector('[role=switch]').click();await until(()=>subscription.querySelector('[role=switch]').getAttribute('aria-busy')==='true');fixture.complete();await until(()=>subscription.querySelector('[role=switch]').getAttribute('aria-checked')==='false');subscription.querySelector('.plugin-settings-button').click();await until(()=>dialog());const subscriptionDetail=document.querySelector('[data-plugin-details="provider.codex"]');check(fixture.legacyMounts===0 && subscriptionDetail.textContent.includes('启用插件后可调整设置'),'Disabled plugin explanation opens without running settings');subscriptionDetail.querySelector('[role=switch]').click();await until(()=>subscriptionDetail.querySelector('[role=switch]').getAttribute('aria-busy')==='true');fixture.complete();await until(()=>fixture.legacyMounts===1 && subscriptionDetail.querySelector('[data-legacy-settings]'));close();await until(()=>!dialog());
  provider.querySelector('.plugin-row-button').click();await until(()=>dialog());check(child.getAttribute('aria-checked')==='false' && draft.value==='未保存的插件草稿' && fixture.mounts===1,'Reopening retains child choice and draft');close();await until(()=>!dialog());
  branches[1].focus();check(fixture.errors.length===0,fixture.errors.join(','));return {mounts:fixture.mounts,legacyMounts:fixture.legacyMounts,writes:fixture.writes.length,branches:branches.length};
 }.toString()+')()');
 win.webContents.focus();win.webContents.sendInputEvent({type:'keyDown',keyCode:'Enter'});win.webContents.sendInputEvent({type:'char',keyCode:'\r'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Enter'});
 await win.webContents.executeJavaScript('new Promise((resolve,reject)=>{const end=performance.now()+2000;const poll=()=>{const b=document.querySelector("[data-plugin-group=tools] .plugin-branch-toggle");if(b.getAttribute("aria-expanded")==="false")resolve();else if(performance.now()>end)reject(new Error("Enter did not fold branch"));else setTimeout(poll,10);};poll();})');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Space'});win.webContents.sendInputEvent({type:'char',keyCode:' '});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Space'});
 await win.webContents.executeJavaScript('new Promise((resolve,reject)=>{const end=performance.now()+2000;const poll=()=>{const b=document.querySelector("[data-plugin-group=tools] .plugin-branch-toggle");if(b.getAttribute("aria-expanded")==="true")resolve();else if(performance.now()>end)reject(new Error("Space did not open branch"));else setTimeout(poll,10);};poll();})');
 await win.webContents.executeJavaScript('document.querySelector(".content-scroll").scrollTop=50;document.querySelector("[data-plugin=\\"provider.newapi\\"] .plugin-row-button").focus({preventScroll:true})');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Enter'});win.webContents.sendInputEvent({type:'char',keyCode:'\r'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Enter'});
 await win.webContents.executeJavaScript('('+async function(){const end=performance.now()+2000;while(!Array.from(document.querySelectorAll('.plugin-details-modal')).some(dialog=>!dialog.closest('[hidden],[inert]') && dialog.contains(document.activeElement))){if(performance.now()>end)throw new Error('Keyboard row did not open dialog');await new Promise(r=>setTimeout(r,10));}const dialog=Array.from(document.querySelectorAll('.plugin-details-modal')).find(element=>!element.closest('[hidden],[inert]'));fixture.tabStops=Array.from(dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')).filter(element=>!element.closest('[hidden],[inert]') && element.getBoundingClientRect().height);fixture.tabStops.at(-1).focus();}.toString()+')()');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Tab'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Tab'});
 await win.webContents.executeJavaScript('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))).then(()=>{if(document.activeElement!==fixture.tabStops[0])throw new Error("Tab escaped dialog instead of wrapping to first control");})');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Tab',modifiers:['shift']});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Tab',modifiers:['shift']});
 await win.webContents.executeJavaScript('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))).then(()=>{if(document.activeElement!==fixture.tabStops.at(-1))throw new Error("Shift+Tab escaped dialog instead of wrapping to last control");})');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
 await win.webContents.executeJavaScript('('+async function(){const end=performance.now()+2000;while(Array.from(document.querySelectorAll('.plugin-details-modal')).some(dialog=>!dialog.closest('[hidden],[inert]'))){if(performance.now()>end)throw new Error('Escape did not close plugin dialog');await new Promise(r=>setTimeout(r,10));}if(document.activeElement!==document.querySelector('[data-plugin="provider.newapi"] .plugin-row-button') || document.querySelector('.content-scroll').scrollTop!==50)throw new Error('Escape failed to restore trigger and scroll');document.querySelector('[data-plugin="provider.newapi"] .plugin-settings-button').click();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}.toString()+')()');
 win.webContents.sendInputEvent({type:'mouseDown',x:5,y:5,button:'left',clickCount:1});win.webContents.sendInputEvent({type:'mouseUp',x:5,y:5,button:'left',clickCount:1});
 await win.webContents.executeJavaScript('('+async function(){const end=performance.now()+2000;while(Array.from(document.querySelectorAll('.plugin-details-modal')).some(dialog=>!dialog.closest('[hidden],[inert]'))){if(performance.now()>end)throw new Error('Backdrop click did not close plugin dialog');await new Promise(r=>setTimeout(r,10));}await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));if(document.activeElement!==document.querySelector('[data-plugin="provider.newapi"] .plugin-settings-button'))throw new Error('Backdrop failed to restore settings button: '+document.activeElement.outerHTML.slice(0,240));}.toString()+')()');
 await win.webContents.executeJavaScript('document.querySelector("[data-plugin=\\"provider.newapi\\"] .plugin-row-button").click();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))).then(()=>{document.querySelector("[aria-label=\\"插件草稿\\"]").focus();fixture.openGlobal();})');
 await win.webContents.executeJavaScript('('+async function(){const end=performance.now()+2000;while(!document.querySelector('[role=dialog][aria-label="全局账户窗口"]')?.contains(document.activeElement)){if(performance.now()>end)throw new Error('Later global modal did not receive focus');await new Promise(r=>setTimeout(r,10));}const global=document.querySelector('[role=dialog][aria-label="全局账户窗口"]'),detail=document.querySelector('.plugin-details-modal'),close=global.querySelector('[aria-label="关闭弹窗"]'),box=close.getBoundingClientRect(),hit=document.elementFromPoint(box.left+box.width/2,box.top+box.height/2);if(!global.contains(hit) || parseFloat(getComputedStyle(global.parentElement).zIndex)<=parseFloat(getComputedStyle(detail.parentElement).zIndex))throw new Error('Later root modal is visually obscured by plugin details');}.toString()+')()');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
 await win.webContents.executeJavaScript('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))).then(()=>{const detail=document.querySelector(".plugin-details-modal");if(document.querySelector("[role=dialog][aria-label=\\"全局账户窗口\\"]") || detail.closest("[hidden],[inert]") || document.activeElement!==detail.querySelector("[aria-label=\\"插件草稿\\"]"))throw new Error("First Escape must close only the newer root modal and restore details focus");})');
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
 await win.webContents.executeJavaScript('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))).then(()=>{if(!document.querySelector(".plugin-details-modal").closest("[hidden],[inert]") || document.activeElement!==document.querySelector("[data-plugin=\\"provider.newapi\\"] .plugin-row-button"))throw new Error("Second Escape must close details and restore its row");})');
 for(const width of [1120,680,480]){win.setContentSize(width,620);await win.webContents.executeJavaScript('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');await win.webContents.executeJavaScript('('+async function(){const area=document.querySelector('.plugin-settings');if(area.scrollWidth>area.clientWidth+1)throw new Error('Plugin tree overflow '+innerWidth);for(const node of document.querySelectorAll('.plugin-settings-group')){const box=node.getBoundingClientRect();if(!box.height)continue;const control=node.querySelector('[role=switch]'),c=control.getBoundingClientRect();if(c.right>box.right+1 || c.width<40)throw new Error('Switch overflow '+innerWidth);}document.querySelector('[data-plugin="provider.newapi"] .plugin-settings-button').click();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const dialog=Array.from(document.querySelectorAll('.plugin-details-modal')).find(element=>!element.closest('[hidden],[inert]')),box=dialog.getBoundingClientRect();if(box.left<0 || box.right>innerWidth+1 || box.top<0 || box.bottom>innerHeight+1 || dialog.scrollWidth>dialog.clientWidth+1)throw new Error('Plugin dialog exceeds viewport '+innerWidth);const scroller=[dialog,...dialog.querySelectorAll('*')].find(element=>/auto|scroll/.test(getComputedStyle(element).overflowY) && element.scrollHeight>element.clientHeight+1);if(!scroller)throw new Error('Long plugin details have no internal scroll '+innerWidth);scroller.scrollTop=scroller.scrollHeight;if(scroller.scrollTop<=0)throw new Error('Plugin details cannot be scrolled '+innerWidth);const controls=Array.from(dialog.querySelectorAll('button:not(:disabled),input:not(:disabled)')).filter(element=>element.getBoundingClientRect().height);controls.at(-1).focus();await new Promise(r=>requestAnimationFrame(r));const focused=document.activeElement.getBoundingClientRect();if(focused.top<box.top || focused.bottom>box.bottom+1)throw new Error('Keyboard cannot reach detail control '+innerWidth);dialog.querySelector('[aria-label="关闭弹窗"]').click();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}.toString()+')()');}
 win.setContentSize(1120,900);await win.webContents.executeJavaScript('document.querySelector(".content-scroll").scrollTop=0;document.activeElement.blur();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');fs.writeFileSync(path.resolve(__dirname,'..','plugin-settings-tree.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
 await win.webContents.executeJavaScript('document.documentElement.dataset.theme="dark";new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');fs.writeFileSync(path.resolve(__dirname,'..','plugin-settings-tree-dark.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
 await win.webContents.executeJavaScript('document.documentElement.dataset.theme="light";document.querySelector("[data-plugin=\\"provider.newapi\\"] .plugin-settings-button").click();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');fs.writeFileSync(path.resolve(__dirname,'..','plugin-settings-details.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
 win.setContentSize(480,620);await win.webContents.executeJavaScript('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');fs.writeFileSync(path.resolve(__dirname,'..','plugin-settings-details-480.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
 console.log('PLUGIN_TREE_RESULT '+JSON.stringify(result));win.destroy();app.exit(0);
}).catch(error=>{console.error(error.stack || error);app.exit(1);});`);
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
  const child=spawn(electron,[path.join(root,'audit.cjs')],{env,windowsHide:true,stdio:['ignore','pipe','pipe'],signal:t.signal});let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);
  const code=await new Promise<number|null>((resolve,reject)=>{child.once('error',reject);child.once('close',resolve);});assert.equal(code,0,stderr+stdout);
  const result=stdout.split(/\r?\n/).find(line=>line.startsWith('PLUGIN_TREE_RESULT '));assert.ok(result,stdout);assert.deepEqual(JSON.parse(result.slice('PLUGIN_TREE_RESULT '.length)),{mounts:1,legacyMounts:1,writes:4,branches:3});
});
