import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {PopupLayer} from '../src/components/Popup';

test('public popup layer renders without a browser document',()=>{
  assert.match(renderToStaticMarkup(createElement(PopupLayer,{label:'Server popup',onClose:()=>{},children:createElement('span',null,'Content')})),/data-popup-kind="dialog"/);
});

test('public dialog and popover share top-layer dismissal, animated draft retention and immediate scope revocation',{timeout:30000},async t=>{
  let electron:string;try{electron=createRequire(import.meta.url)('electron');}catch{return t.skip('Electron unavailable');}if(!existsSync(electron))return t.skip('Electron unavailable');
  await mkdir('.test-data',{recursive:true});const directory=await mkdtemp(path.resolve('.test-data/popup-layer-'));t.after(()=>rm(directory,{recursive:true,force:true,maxRetries:5,retryDelay:100}));
  const script=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React,{useRef,useState} from 'react';import {createRoot} from 'react-dom/client';import {flushSync} from 'react-dom';import {Modal} from './src/components/ui';import {PopupLayer} from './src/components/Popup';import {PopupPresence,PopupScope} from './src/components/PopupPresence';
window.fixture={errors:[],mounts:0,unmounts:0,busy:false,act:flushSync};addEventListener('error',event=>fixture.errors.push(event.message));addEventListener('unhandledrejection',event=>fixture.errors.push(String(event.reason)));
function Draft(){const [value,setValue]=useState('draft');React.useEffect(()=>{fixture.mounts++;return()=>fixture.unmounts++;},[]);return <input style={{color:'var(--popup-test-accent)'}} aria-label="Retained draft" value={value} onChange={event=>setValue(event.target.value)}/>;}
function App(){const [open,setOpen]=useState(true),[visited,setVisited]=useState(true),[filter,setFilter]=useState(false),[scope,setScope]=useState('account-a');const trigger=useRef(null),anchor=useRef(null),search=useRef(null);fixture.revoke=()=>setScope('account-b');fixture.changeScope=setScope;fixture.closeParent=()=>setOpen(false);fixture.openFilter=()=>setFilter(true);return <main className="desktop-shell" style={{display:'block','--popup-test-accent':'rgb(77,88,99)'}}><PopupScope scope={scope}><button id="popup-trigger" ref={trigger} onClick={()=>{setVisited(true);setOpen(true);}}>Open</button>{visited && <Modal title="Retained parent" open={open} returnFocus={trigger.current} onClose={()=>{if(!fixture.busy)setOpen(false);}}><Draft/><button id="filter-trigger" ref={anchor} onClick={()=>setFilter(true)}>Filter</button><PopupPresence>{filter && <PopupLayer kind="popover" label="Shared filter" className="popup-filter" style={{position:'fixed',left:400,top:100,width:200}} initialFocus={search} returnFocus={anchor.current} anchorRef={anchor} onClose={()=>setFilter(false)}><input ref={search} aria-label="Filter search"/><button id="filter-apply" onClick={()=>setFilter(false)}>Apply</button></PopupLayer>}</PopupPresence></Modal>}</PopupScope></main>;}
createRoot(document.getElementById('root')).render(<App/>);`},bundle:true,platform:'browser',format:'esm',write:false,loader:{'.svg':'text'},define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'});
  await writeFile(path.join(directory,'app.js'),script.outputFiles[0].contents);
  const styles=await Promise.all(['components/segmented-switch.css','styles.css','theme-tokens.css','theme.css','filters-tools-motion.css'].map(file=>readFile(path.resolve('src',file),'utf8')));await writeFile(path.join(directory,'style.css'),styles.join('\n')+'\n.popup-filter{background:var(--panel);padding:20px;border:1px solid var(--border);border-radius:12px}.popup-filter.open{animation:picker-open .16s ease-out}.popup-filter.closing{animation:picker-close .13s ease-in forwards;pointer-events:none}');
  await writeFile(path.join(directory,'index.html'),'<html><head><meta charset="UTF-8"><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script type="module" src="app.js"></script></body></html>');
  await writeFile(path.join(directory,'main.cjs'),String.raw`
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path');for(const name of ['userData','sessionData','logs','crashDumps']){const directory=path.join(__dirname,name);fs.mkdirSync(directory,{recursive:true});app.setPath(name,directory);}app.disableHardwareAcceleration();app.whenReady().then(async()=>{
const win=new BrowserWindow({width:1100,height:800,show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});await win.loadFile(path.join(__dirname,'index.html'));win.webContents.debugger.attach('1.3');await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
const run=code=>win.webContents.executeJavaScript(code);const check=async code=>run('('+async function(code){const until=async fn=>{const end=performance.now()+5000;while(!fn()){if(performance.now()>end)throw new Error('Popup timeout: '+fn+' '+fixture.errors);await new Promise(resolve=>setTimeout(resolve,10));}};const assert=(value,message)=>{if(!value)throw new Error(message);};await eval('(async()=>{'+code+'})()');}.toString()+')('+JSON.stringify(code)+')');
await check('await until(()=>document.activeElement?.closest("[aria-label=\\\"Retained parent\\\"]"));const initial=document.querySelector("[aria-label=\\\"Retained draft\\\"]");assert(initial.closest(".desktop-shell"),"Initially open popup missed its themed shell");assert(getComputedStyle(initial).color==="rgb(77, 88, 99)" && fixture.mounts===1,"Initial portal remounted drafts or lost theme");fixture.act(()=>fixture.closeParent());await until(()=>document.querySelector("[aria-label=\\\"Retained parent\\\"]").closest(".modal-overlay").hidden);');
await check('await until(()=>document.querySelector("#popup-trigger"));document.querySelector("#popup-trigger").focus();document.querySelector("#popup-trigger").click();await until(()=>document.activeElement?.closest("[aria-label=\\\"Retained parent\\\"]"));const draft=document.querySelector("[aria-label=\\\"Retained draft\\\"]");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(draft,"keep this draft");draft.dispatchEvent(new Event("input",{bubbles:true}));fixture.draft=draft;document.querySelector("#filter-trigger").click();await until(()=>document.activeElement?.getAttribute("aria-label")==="Filter search");const popover=document.querySelector("[aria-label=\\\"Shared filter\\\"]"),parent=document.querySelector("[aria-label=\\\"Retained parent\\\"]").closest(".modal-overlay");assert(Number(getComputedStyle(popover).zIndex)>Number(getComputedStyle(parent).zIndex),"Popover is below parent");');
// Real pointerdown/mousedown/mouseup must dismiss just the top popup, even over the parent backdrop.
win.webContents.sendInputEvent({type:'mouseDown',x:5,y:5,button:'left',clickCount:1});win.webContents.sendInputEvent({type:'mouseUp',x:5,y:5,button:'left',clickCount:1});
await check('await until(()=>!document.querySelector("[aria-label=\\\"Shared filter\\\"]"));assert(document.querySelector("[aria-label=\\\"Retained parent\\\"]").getAttribute("aria-hidden")!=="true","One backdrop click closed both layers");assert(document.querySelector("[aria-label=\\\"Retained draft\\\"]").value==="keep this draft","Outside dismissal lost parent draft");assert(document.activeElement===document.querySelector("#filter-trigger"),"Backdrop dismissal lost popover anchor focus");fixture.act(()=>fixture.openFilter());await until(()=>document.querySelector("[aria-label=\\\"Shared filter\\\"]"));fixture.act(()=>document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true})));await until(()=>!document.querySelector("[aria-label=\\\"Shared filter\\\"]"));assert(document.activeElement===document.querySelector("#filter-trigger"),"Escape did not restore anchor focus");');
await check('fixture.act(()=>fixture.closeParent());const parent=document.querySelector("[aria-label=\\\"Retained parent\\\"]"),overlay=parent.closest(".modal-overlay");assert(overlay.dataset.popupPhase==="exiting" && overlay.inert && parent.getAttribute("aria-hidden")==="true","Retained close bypassed animation or remained interactive");const animation=overlay.getAnimations()[0];assert(animation,"Retained close has no animation");animation.pause();animation.currentTime=80;assert(Number(getComputedStyle(overlay).opacity)>0 && Number(getComputedStyle(overlay).opacity)<1,"Retained exit has no intermediate opacity");document.querySelector("#popup-trigger").click();await until(()=>overlay.dataset.popupPhase==="open");await new Promise(resolve=>setTimeout(resolve,300));assert(!overlay.hidden && document.querySelector("[aria-label=\\\"Retained draft\\\"]")===fixture.draft,"Rapid reopen lost retained component");fixture.act(()=>fixture.closeParent());await until(()=>overlay.hidden);assert(fixture.mounts===1 && fixture.unmounts===0 && fixture.draft.value==="keep this draft","Closed dialog remounted drafts");assert(document.activeElement===document.querySelector("#popup-trigger"),"Retained close lost trigger focus");document.querySelector("#popup-trigger").click();await until(()=>!overlay.hidden);fixture.act(()=>fixture.openFilter());await until(()=>document.querySelector("[aria-label=\\\"Shared filter\\\"]"));fixture.act(()=>fixture.closeParent());assert(!document.querySelector("[aria-label=\\\"Shared filter\\\"]"),"Closing parent retained its popover portal");await until(()=>overlay.hidden);document.querySelector("#popup-trigger").click();await until(()=>!overlay.hidden);fixture.act(()=>fixture.revoke());assert(!document.querySelector("[aria-label=\\\"Retained draft\\\"]") && !document.querySelector("[aria-label=\\\"Retained parent\\\"]"),"Scope revocation retained private content");document.querySelector("#popup-trigger").click();await until(()=>document.querySelector("[aria-label=\\\"Retained draft\\\"]"));assert(document.querySelector("[aria-label=\\\"Retained draft\\\"]").value==="draft","New scope inherited old draft");assert(fixture.errors.length===0,"Renderer errors "+fixture.errors);');
await check('fixture.busy=true;fixture.act(()=>fixture.changeScope("account-c"));assert(!document.querySelector("[aria-label=\\\"Retained draft\\\"]"),"Busy scope revocation retained draft");fixture.act(()=>fixture.changeScope("account-b"));assert(!document.querySelector("[aria-label=\\\"Retained draft\\\"]"),"Returning to old scope revived a busy draft");fixture.busy=false;fixture.act(()=>fixture.closeParent());document.querySelector("#popup-trigger").click();await until(()=>document.querySelector("[aria-label=\\\"Retained draft\\\"]"));assert(fixture.errors.length===0,"Renderer errors "+fixture.errors);');
await check('const style=document.createElement("style");style.textContent=".modal-overlay{opacity:1!important;animation:none!important}.modal-overlay>.modal{animation:none!important}.modal-overlay::before{content:attr(data-popup-phase);position:absolute;inset:0;animation:modal-backdrop-in 180ms ease both}.modal-overlay[data-popup-phase=exiting]::before{animation:modal-backdrop-out 160ms ease both}";document.head.append(style);await new Promise(resolve=>setTimeout(resolve,200));const overlay=document.querySelector(".modal-overlay");fixture.act(()=>fixture.closeParent());assert(!overlay.hidden && overlay.dataset.popupPhase==="exiting" && overlay.inert,"Pseudo-element-only exit was removed before its animation");assert(overlay.getAnimations().length===0 && overlay.getAnimations({subtree:true}).length>0,"Fixture must animate only its pseudo-element");await until(()=>overlay.hidden);assert(document.activeElement===document.querySelector("#popup-trigger"),"Pseudo-element exit lost trigger focus");assert(fixture.errors.length===0,"Renderer errors "+fixture.errors);');
console.log('POPUP_RESULT '+JSON.stringify({mixed:true,retained:true,animated:true,revoked:true,pseudoExit:true}));win.destroy();app.exit(0);}).catch(error=>{console.error(error.stack || error);app.exit(1);});`);
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const child=spawn(electron,[path.join(directory,'main.cjs')],{env,windowsHide:true,stdio:['ignore','pipe','pipe'],signal:t.signal});let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);
  const code=await new Promise<number|null>((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});assert.equal(code,0,stderr+stdout);assert.match(stdout,/POPUP_RESULT.*"mixed":true.*"retained":true.*"animated":true.*"revoked":true/);
});
