import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import path from 'node:path';

test('continuous switches animate and drag pressed buttons and checked radios, with cancel and keyboard selection',{timeout:30000},async t=>{
  const electron=createRequire(import.meta.url)('electron') as string;if(!existsSync(electron))return t.skip('Electron unavailable');
  await mkdir('.test-data',{recursive:true});const root=await mkdtemp(path.resolve('.test-data/continuous-switch-'));t.after(()=>rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100}));
  const built=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {SegmentedSwitch} from './src/components/ui';
window.fixture={writes:[]};function App(){const [pressed,setPressed]=useState(0),[checked,setChecked]=useState(0);return <>{['pressed','checked'].map(kind=><SegmentedSwitch key={kind} label={kind} role={kind==='checked' ? 'radiogroup' : 'group'}>{['All','OpenAI','Anthropic'].map((name,index)=><button type="button" key={name} {...kind==='checked' ? {role:'radio','aria-checked':checked===index,tabIndex:checked===index ? 0 : -1} : {'aria-pressed':pressed===index}} onClick={()=>{fixture.writes.push([kind,index]);(kind==='checked' ? setChecked : setPressed)(index);}}>{name}</button>)}</SegmentedSwitch>)}</>;};createRoot(document.getElementById('root')).render(<App/>);`},bundle:true,platform:'browser',format:'esm',write:false,loader:{'.css':'empty','.svg':'text'},define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'});
  await writeFile(path.join(root,'app.js'),built.outputFiles[0].contents);
  await writeFile(path.join(root,'style.css'),await readFile('src/models-market.css','utf8')+'\nbody{padding:20px;background:#eef3fa}button{font:inherit}.model-mode-selector{--border:#aac;--panel-soft:#eee;--text-secondary:#224;--accent:#66c;--panel-strong:#ccd}');
  await writeFile(path.join(root,'index.html'),'<html><head><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script type="module" src="app.js"></script></body></html>');
  await writeFile(path.join(root,'main.cjs'),String.raw`
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path');for(const name of ['userData','sessionData','logs','crashDumps']){const p=path.join(__dirname,name);fs.mkdirSync(p,{recursive:true});app.setPath(name,p);}app.disableHardwareAcceleration();
app.whenReady().then(async()=>{const win=new BrowserWindow({width:560,height:360,show:process.platform==='darwin',frame:process.platform!=='darwin',webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false,offscreen:process.platform!=='darwin'}});await win.loadFile(path.join(__dirname,'index.html'));win.webContents.debugger.attach('1.3');await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
const run=async(fn,...args)=>{const r=await win.webContents.executeJavaScript('(async()=>{try{return {ok:true,value:await ('+fn.toString()+')(...'+JSON.stringify(args)+')}}catch(e){return {ok:false,error:e.stack||String(e)}}})()');if(!r.ok)throw new Error(r.error);return r.value;},settle=()=>run(()=>new Promise(r=>setTimeout(r,280)));
await run(async()=>{const end=performance.now()+3000;while(document.querySelectorAll('.segmented-thumb').length<2){if(performance.now()>end)throw new Error('Switches missing');await new Promise(r=>setTimeout(r,10));}});
for(const kind of ['pressed','checked']){
 const p=await run(kind=>{const node=document.querySelector('[aria-label='+kind+']'),r=index=>{const b=node.querySelectorAll('button')[index].getBoundingClientRect();return {x:Math.round(b.left+b.width/2),y:Math.round(b.top+b.height/2)};};return {from:r(0),to:r(2),writes:fixture.writes.length};},kind);
 win.webContents.focus();win.webContents.sendInputEvent({type:'mouseMove',...p.from});win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...p.from});win.webContents.sendInputEvent({type:'mouseMove',modifiers:['leftButtonDown'],...p.to});await settle();
 await run((kind,writes)=>{if(!document.querySelector('[aria-label='+kind+'][data-dragging]') || fixture.writes.length!==writes)throw new Error('Drag must preview');},kind,p.writes);
 win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...p.to});await settle();await run((kind,writes)=>{const node=document.querySelector('[aria-label='+kind+']');if(fixture.writes.length!==writes+1 || node.querySelectorAll('button')[2].getAttribute(kind==='checked' ? 'aria-checked' : 'aria-pressed')!=='true')throw new Error('Drag did not select once');},kind,p.writes);
 win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...p.to});win.webContents.sendInputEvent({type:'mouseMove',modifiers:['leftButtonDown'],...p.from});await settle();win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...p.from});await settle();await run((kind,writes)=>{if(fixture.writes.length!==writes+1 || document.querySelector('[aria-label='+kind+'][data-dragging]'))throw new Error('Cancelled drag wrote');},kind,p.writes);
 await run(kind=>document.querySelector('[aria-label='+kind+'] button').click(),kind);await run(async kind=>{const thumb=document.querySelector('[aria-label='+kind+'] .segmented-thumb'),animation=thumb.getAnimations().find(a=>a.effect.getKeyframes().some(frame=>frame.transform));if(!animation)throw new Error('Sliding animation absent '+JSON.stringify({kind,style:getComputedStyle(thumb).cssText,transition:getComputedStyle(thumb).transition,transform:getComputedStyle(thumb).transform,writes:fixture.writes,node:thumb.parentElement.outerHTML}));animation.pause();animation.currentTime=45;await new Promise(r=>requestAnimationFrame(r));const early=thumb.getBoundingClientRect().x;animation.currentTime=165;await new Promise(r=>requestAnimationFrame(r));if(Math.abs(thumb.getBoundingClientRect().x-early)<5)throw new Error('No intermediate slide');animation.finish();},kind);await settle();
 await run(kind=>document.querySelector('[aria-label='+kind+'] button').focus(),kind);win.webContents.sendInputEvent({type:'keyDown',keyCode:'End'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'End'});await settle();await run(kind=>{const button=document.querySelector('[aria-label='+kind+']').querySelectorAll('button')[2];if(document.activeElement!==button || button.getAttribute(kind==='checked' ? 'aria-checked' : 'aria-pressed')!=='true')throw new Error('Keyboard End failed');},kind);
}
console.log('CONTINUOUS_SWITCH_OK');win.destroy();app.exit(0);}).catch(error=>{console.error(error.stack||error);app.exit(1);});`);
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;const child=spawn(electron,[path.join(root,'main.cjs')],{env,windowsHide:true,stdio:['ignore','pipe','pipe'],signal:t.signal});let log='';child.stdout.on('data',chunk=>log+=chunk);child.stderr.on('data',chunk=>log+=chunk);const code=await new Promise<number|null>((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});assert.equal(code,0,log);assert.match(log,/CONTINUOUS_SWITCH_OK/);
});
