import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';

test('real tool page withdraws prepared and late previews without remounting the other adapter, and preserves disabled backups',{timeout:30000},async t=>{
  let electron:string;try{electron=createRequire(import.meta.url)('electron');}catch{return t.skip('Electron runtime unavailable');}if(!existsSync(electron))return t.skip('Electron runtime unavailable');
  const base=path.resolve('.test-data');await mkdir(base,{recursive:true});const root=await mkdtemp(path.join(base,'tools-plugin-ui-'));t.after(()=>rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100}));
  const built=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React,{useState} from 'react';import {createRoot} from 'react-dom/client';
import {AppContext} from './src/context';import {DEFAULT_PREFERENCES} from './shared/types';import {applyPreferencePatch} from './shared/selections';
import {builtinManifests} from './plugins/manifests';import {settingsGroups} from './shared/plugin-preferences';
const prefs=structuredClone(DEFAULT_PREFERENCES);prefs.sites[0]={...prefs.sites[0],url:'https://fixture.invalid',userId:1,accessTokenConfigured:true};prefs.bindings=prefs.bindings.map(binding=>({...binding,model:'fixture-'+binding.tool,group:'standard'}));
const dashboard={status:{system_name:'Fixture',quota_per_unit:500000},user:{id:1,username:'fixture',display_name:'Fixture',quota:0,used_quota:0,request_count:0,group:'standard'},logs:{items:[],total:0,page:1,pageSize:15},series:[],stat:null,tokens:[],warnings:[],fetchedAt:1,days:7,catalog:{models:['codex','claude'].map(tool=>({model_name:'fixture-'+tool,quota_type:0,model_ratio:1,model_price:0,completion_ratio:1,enable_groups:['standard'],supported_endpoint_types:[]})),groupRatio:{standard:1},usableGroups:{standard:'标准渠道'},autoGroups:[],vendors:[]}};
window.fixture={requests:[],runtimeRequests:[],runtimeListeners:new Set(),restores:[],backupReads:0,notices:[],errors:[],progressListeners:new Set()};
fixture.preview=index=>{const request=fixture.requests[index];request.resolve({id:'preview-'+index,tool:request.input.tool,files:[{path:'C:/fixture/'+request.input.tool+'/config',before:'original',after:'fixture model'}],changes:['测试变更'],expiresAt:Date.now()+600000,token:{id:1,name:'FixtureToken',group:'standard',created:false}});};
fixture.runtime=(index,version)=>{const request=fixture.runtimeRequests[index];request.resolve([...request.tools,...(request.tools.includes('codex') ? ['chatgpt'] : [])].map(tool=>({tool,installed:true,version,checkedAt:Date.now(),npmAvailable:true,nodeVersion:'24.18.0',phase:'idle'})));};
window.addEventListener('error',event=>fixture.errors.push(event.message));window.addEventListener('unhandledrejection',event=>fixture.errors.push(String(event.reason)));
const matchMedia=window.matchMedia.bind(window);window.matchMedia=query=>query.includes('prefers-reduced-motion') ? {...matchMedia(query),matches:true} : matchMedia(query);
window.lumi={toolRuntimes:force=>new Promise(resolve=>fixture.runtimeRequests.push({resolve,force,tools:[...fixture.enabledTools]})),onToolRuntime:listener=>{fixture.runtimeListeners.add(listener);return()=>fixture.runtimeListeners.delete(listener);},onConfigProgress:listener=>{fixture.progressListeners.add(listener);return()=>fixture.progressListeners.delete(listener);},previewConfig:input=>new Promise(resolve=>fixture.requests.push({input,resolve})),backups:async()=>{fixture.backupReads++;return ['codex','claude'].map(tool=>({id:'backup-'+tool,tool,createdAt:1,paths:['C:/fixture/'+tool+'/config']}));},restoreBackup:async id=>{fixture.restores.push(id);return[];}};
const {default:Tools}=await import('./src/pages/Tools'),{PluginSettingsProvider,PluginSettingsSection}=await import('./src/host/plugins'),{ToolConfigViewsProvider}=await import('./src/host/tool-config'),{toolConfigContributions}=await import('./src/host/renderer-registry');
function Host(){
 const [preferences,setPreferences]=useState(prefs),[statuses,setStatuses]=useState(()=>builtinManifests.map(manifest=>({manifest,state:'active',generation:1}))),[page,setPage]=useState('tools');
 fixture.showPage=setPage;fixture.preferences=preferences;
 fixture.switchSite=()=>setPreferences(current=>({...current,activeSiteId:'fixture-other',sites:[...current.sites,{...current.sites[0],id:'fixture-other'}]}));
 fixture.setEnabled=(id,enabled)=>setStatuses(all=>all.map(status=>status.manifest.id===id ? {...status,state:enabled ? 'active' : 'disabled',generation:status.generation+1} : status));
 fixture.enabledTools=['codex','claude'].filter(tool=>statuses.some(status=>status.manifest.id==='adapter.tool.'+tool && status.state==='active'));
 const items=settingsGroups(statuses.map(status=>status.manifest)).map(group=>({...group,status:statuses.find(status=>status.manifest.id===group.id)}));
 const app={preferences,bootstrap:{preferences,desktop:true,secureStorage:true,version:'fixture',configs:[]},dashboard,page,setPage,openLogin:()=>{},updatePreferences:async patch=>setPreferences(current=>applyPreferencePatch(current,patch)),toast:(message,kind)=>fixture.notices.push({message,kind}),reloadBootstrap:async()=>{}};
 return <AppContext.Provider value={app}><PluginSettingsProvider value={{items,statuses,loading:false,busyId:null,error:'',setEnabled:async()=>{},setView:async()=>{}}}><ToolConfigViewsProvider value={toolConfigContributions(statuses)}>{page==='settings' ? <PluginSettingsSection/> : <Tools/>}</ToolConfigViewsProvider></PluginSettingsProvider></AppContext.Provider>;
}
createRoot(document.getElementById('root')).render(<Host/>);`},bundle:true,platform:'browser',format:'esm',write:false,loader:{'.css':'empty','.svg':'text'},define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'});
  await writeFile(path.join(root,'renderer.js'),built.outputFiles[0].contents);
  const css=await Promise.all(['styles.css','workbench.css','select.css','theme-tokens.css','theme.css','updates-trends.css','filters-tools-motion.css','platform-logs.css','tools-progress.css','models-market.css'].map(file=>readFile(path.resolve('src',file),'utf8')));
  await writeFile(path.join(root,'style.css'),css.join('\n')+'\nbody{overflow:auto;padding:24px;background:var(--background)}*{animation:none!important;transition:none!important}');
  await writeFile(path.join(root,'index.html'),'<html data-theme="light"><head><meta charset="UTF-8"><link rel="stylesheet" href="style.css"></head><body><div id="root"></div><script type="module" src="renderer.js"></script></body></html>');
  await writeFile(path.join(root,'audit.cjs'),String.raw`
const {app,BrowserWindow}=require('electron'),path=require('node:path'),fs=require('node:fs');
for(const name of ['userData','sessionData','logs','crashDumps']){const directory=path.join(__dirname,name);fs.mkdirSync(directory,{recursive:true});app.setPath(name,directory);}
app.disableHardwareAcceleration();app.whenReady().then(async()=>{
 const win=new BrowserWindow({show:false,width:1180,height:900,webPreferences:{offscreen:true,sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});win.webContents.on('console-message',event=>console.log('RENDERER '+event.message));await win.loadFile(path.join(__dirname,'index.html'));
 const result=await win.webContents.executeJavaScript('('+async function(){
  const check=(value,message)=>{if(!value)throw new Error(message);},until=async fn=>{const end=performance.now()+4000;while(!fn()){if(performance.now()>end)throw new Error('Tool adapter UI timeout: '+fn.toString());await new Promise(resolve=>setTimeout(resolve,10));}},settle=()=>new Promise(resolve=>setTimeout(resolve,40));
  const toolCard=tool=>document.querySelector('[aria-label="'+tool+' 目标模型"]')?.closest('.tool-config-card'),submit=tool=>toolCard(tool).querySelector('form').requestSubmit(),dialog=title=>Array.from(document.querySelectorAll('[role=dialog]')).find(element=>element.querySelector('h2')?.textContent===title),button=(label,area=document)=>Array.from(area.querySelectorAll('button')).find(element=>element.textContent.trim()===label);
  await until(()=>toolCard('codex') && toolCard('claude') && !toolCard('codex').querySelector('[type=submit]').disabled && fixture.runtimeRequests.length===1);
  const claude=toolCard('claude'),draft=document.getElementById('claude-context-window');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(draft,'123');draft.dispatchEvent(new Event('input',{bubbles:true}));await settle();
  const retained=()=>check(toolCard('claude')===claude && document.getElementById('claude-context-window')===draft && draft.value==='123','Withdrawing Codex remounted Claude or lost its uncommitted draft');
  submit('codex');await until(()=>fixture.requests.length===1);check(toolCard('claude').querySelector('[type=submit]').disabled,'Shared request lock');fixture.preview(0);await until(()=>dialog('确认配置变更'));fixture.setEnabled('adapter.tool.codex',false);await until(()=>!toolCard('codex') && !dialog('确认配置变更') && fixture.runtimeRequests.length===2);retained();check(fixture.restores.length===0,'Withdrawal did not mutate files');
  check(fixture.runtimeRequests[1].tools.join(',')==='claude','New runtime inspection excludes disabled Codex');fixture.runtime(1,'2.0.0');await until(()=>claude.querySelector('.tool-runtime').textContent.includes('2.0.0'));fixture.runtime(0,'1.0.0');await settle();check(claude.querySelector('.tool-runtime').textContent.includes('2.0.0') && !claude.querySelector('.tool-runtime').textContent.includes('1.0.0'),'Old runtime response cannot overwrite current scope');
  fixture.setEnabled('adapter.tool.codex',true);await until(()=>toolCard('codex') && !toolCard('codex').querySelector('[type=submit]').disabled && fixture.runtimeRequests.length===3);retained();fixture.runtime(2,'3.0.0');await until(()=>toolCard('codex').querySelector('.tool-runtime').textContent.includes('3.0.0'));submit('codex');await until(()=>fixture.requests.length===2);
  fixture.setEnabled('adapter.tool.codex',false);await until(()=>!toolCard('codex') && fixture.runtimeRequests.length===4);retained();check(toolCard('claude').querySelector('[type=submit]').disabled,'Revoked pending request still holds global lock until settlement');
  fixture.setEnabled('adapter.tool.codex',true);await until(()=>toolCard('codex') && fixture.runtimeRequests.length===5);retained();check(toolCard('codex').querySelector('[type=submit]').disabled,'Re-enabled adapter cannot bypass in-flight lock');fixture.runtime(4,'5.0.0');await until(()=>claude.querySelector('.tool-runtime').textContent.includes('5.0.0'));fixture.runtime(3,'4.0.0');await settle();check(claude.querySelector('.tool-runtime').textContent.includes('5.0.0'),'Latest detection wins after re-enable');fixture.preview(1);await settle();
  check(!dialog('确认配置变更'),'A response from a revoked adapter revived after re-enable');await until(()=>!toolCard('claude').querySelector('[type=submit]').disabled);retained();
  button('配置备份').click();await until(()=>dialog('配置备份'));fixture.setEnabled('adapter.tool.codex',false);await until(()=>!toolCard('codex') && fixture.runtimeRequests.length===6);retained();
  const rows=Array.from(dialog('配置备份').querySelectorAll('.backup-list>div')),codexBackup=rows.find(row=>row.querySelector('strong').textContent==='Codex'),claudeBackup=rows.find(row=>row.querySelector('strong').textContent==='Claude Code');
  check(codexBackup && claudeBackup,'Disabled adapter backups remain listed');check(button('恢复',codexBackup).disabled && button('恢复',codexBackup).title.includes('启用'),'Disabled adapter restore explained and disabled');check(!button('恢复',claudeBackup).disabled,'Other adapter restore remains available');button('恢复',codexBackup).click();await settle();check(fixture.restores.length===0 && dialog('配置备份'),'Disabled restore does not run');
  button('恢复',claudeBackup).click();await until(()=>dialog('恢复配置'));fixture.setEnabled('adapter.tool.claude',false);await until(()=>!dialog('恢复配置') && !toolCard('claude'));check(fixture.restores.length===0,'Prepared restore revoked without applying');await settle();check(fixture.runtimeRequests.length===6,'No runtime query with both adapters disabled');fixture.runtime(5,'6.0.0');await settle();check(!toolCard('claude'),'Old runtime query does not revive a disabled adapter');
  button('配置备份').click();await until(()=>dialog('配置备份'));check(dialog('配置备份').querySelectorAll('.backup-list>div').length===2 && Array.from(dialog('配置备份').querySelectorAll('.backup-list button')).every(element=>element.disabled),'All backups remain accessible while both adapters disabled');check(document.body.textContent.includes('暂无启用的工具配置插件'),'No adapter guidance');
  fixture.setEnabled('adapter.tool.codex',true);fixture.setEnabled('adapter.tool.claude',true);fixture.showPage('settings');await until(()=>document.querySelector('.plugin-settings-overview'));
  document.querySelector('[data-plugin="adapter.tool.codex"] .plugin-settings-button').click();await until(()=>dialog('Codex 工具配置 插件设置')?.querySelector('[aria-label="Codex 上下文窗口"]'));
  const codexSettings=dialog('Codex 工具配置 插件设置'),context=codexSettings.querySelector('[aria-label="Codex 上下文窗口"]');context.value='1000000';context.dispatchEvent(new Event('change',{bubbles:true}));await until(()=>fixture.preferences.viewSelections[fixture.preferences.activeSiteId]?.['codex.context']===1000000);button('打开工具配置',codexSettings).click();await until(()=>toolCard('codex'));check(!codexSettings.isConnected,'Leaving Settings withdraws its plugin dialog');submit('codex');await until(()=>fixture.requests.length===3);check(fixture.requests[2].input.contextWindow===1000000,'Declared Codex setting feeds next real preview');fixture.preview(2);await until(()=>dialog('确认配置变更'));fixture.showPage('settings');await until(()=>document.querySelector('.plugin-settings-overview'));
  document.querySelector('[data-plugin="adapter.tool.claude"] .plugin-settings-button').click();await until(()=>dialog('Claude Code 工具配置 插件设置')?.querySelector('#claude-context-window'));
  const claudeSettings=dialog('Claude Code 工具配置 插件设置'),claudeContext=claudeSettings.querySelector('#claude-context-window');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(claudeContext,'131072');claudeContext.dispatchEvent(new Event('input',{bubbles:true}));await settle();claudeContext.dispatchEvent(new FocusEvent('focusout',{bubbles:true}));await until(()=>fixture.preferences.viewSelections[fixture.preferences.activeSiteId]?.['claude.context']===131072);claudeSettings.querySelector('[type=checkbox]').click();await until(()=>fixture.preferences.viewSelections[fixture.preferences.activeSiteId]?.['claude.disableAttributionHeader']===false);button('打开工具配置',claudeSettings).click();await until(()=>toolCard('claude'));check(!claudeSettings.isConnected,'Claude navigation withdraws the plugin dialog');submit('claude');await until(()=>fixture.requests.length===4);check(fixture.requests[3].input.contextWindow===131072 && fixture.requests[3].input.disableAttributionHeader===false,'Declared Claude settings feed next real preview');fixture.preview(3);await until(()=>dialog('确认配置变更'));
  check(fixture.requests.length===4 && fixture.errors.length===0,fixture.errors.join(','));return {previews:fixture.requests.length,restores:fixture.restores.length,backupReads:fixture.backupReads};
 }.toString()+')()');
 await win.webContents.executeJavaScript('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');fs.writeFileSync(path.resolve(__dirname,'..','tool-plugin-settings-preview.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
 await win.webContents.executeJavaScript('fixture.showPage("settings");new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
 await win.webContents.executeJavaScript('('+async function(){const end=performance.now()+2000;while(!document.querySelector('[data-plugin="adapter.tool.codex"] .plugin-settings-button')){if(performance.now()>end)throw new Error('Codex settings unavailable');await new Promise(r=>setTimeout(r,10));}document.querySelector('[data-plugin="adapter.tool.codex"] .plugin-settings-button').click();while(!document.querySelector('.plugin-details-modal:not([aria-hidden]) select')){if(performance.now()>end)throw new Error('Codex settings select unavailable');await new Promise(r=>setTimeout(r,10));}fixture.codexDialog=document.querySelector('.plugin-details-modal:not([aria-hidden])');fixture.codexSelect=fixture.codexDialog.querySelector('select');fixture.codexSelect.focus();}.toString()+')()');
 await win.webContents.executeJavaScript('fixture.codexSelect.showPicker();if(!fixture.codexSelect.matches(":open"))throw new Error("Codex picker did not open");',true);
 win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
 await win.webContents.executeJavaScript('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))).then(()=>{if(fixture.codexSelect.matches(":open") || fixture.codexDialog.closest("[hidden],[inert]") || document.activeElement!==fixture.codexSelect)throw new Error("Native picker Escape closed its parent or lost focus");})');
 await win.webContents.executeJavaScript('fixture.codexSelect.showPicker();if(!fixture.codexSelect.matches(":open"))throw new Error("Native picker did not reopen");fixture.codexDialog.querySelector("[aria-label=\\"关闭弹窗\\"]").click();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))',true);
 await win.webContents.executeJavaScript('if(document.querySelector("select:open") || !fixture.codexDialog.closest("[hidden],[inert]"))throw new Error("Closing plugin dialog retained native picker");document.querySelector("[data-plugin=\\"adapter.tool.codex\\"] .plugin-settings-button").click();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
 await win.webContents.executeJavaScript('fixture.codexSelect=fixture.codexDialog.querySelector("select");if(fixture.codexSelect.matches(":open") || fixture.codexSelect.value!=="1000000")throw new Error("Reopening dialog revived picker or lost the selected context");');
 fs.writeFileSync(path.resolve(__dirname,'..','plugin-native-picker-reopened.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
 await win.webContents.executeJavaScript('fixture.codexSelect.focus();fixture.codexSelect.showPicker();fixture.switchSite();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))',true);
 await win.webContents.executeJavaScript('if(fixture.codexDialog.isConnected || fixture.codexSelect.isConnected || document.querySelector("select:open") || document.querySelector(".plugin-details-modal:not([aria-hidden])"))throw new Error("Site change retained plugin dialog, options or native picker");fixture.showPage("tools");new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
 console.log('TOOLS_PLUGIN_UI '+JSON.stringify(result));win.destroy();app.exit(0);
}).catch(error=>{console.error(error.stack || error);app.exit(1);});`);
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
  const child=spawn(electron,[path.join(root,'audit.cjs')],{env,windowsHide:true,stdio:['ignore','pipe','pipe'],signal:t.signal});let stdout='',stderr='';child.stdout.on('data',chunk=>stdout+=chunk);child.stderr.on('data',chunk=>stderr+=chunk);
  const code=await new Promise<number|null>((resolve,reject)=>{child.once('error',reject);child.once('close',resolve);});assert.equal(code,0,stderr+stdout);
  const result=stdout.split(/\r?\n/).find(line=>line.startsWith('TOOLS_PLUGIN_UI '));assert.ok(result,stdout);assert.deepEqual(JSON.parse(result.slice('TOOLS_PLUGIN_UI '.length)),{previews:4,restores:0,backupReads:2});
});
