import {Search,RefreshCw,ChevronRight,Globe2,Minus,Square,X,Boxes,ArrowUpRight,Bell,CheckCircle2,AlertCircle,Info} from 'lucide-react';
import {LoginModal} from '../../../src/components/Login';
import {UpdateNotice} from '../../../src/components/UpdateNotice';
import {Logo,Modal,Pill,Select} from '../../../src/components/ui';
import {useDefaultTheme} from '../../theme.default/renderer';
import type {InterfaceShellProps} from '../../../src/host/interface';
/** Stable interface plugin: all chrome rendering, no account/service or query ownership. */
export default function DefaultInterface(props:InterfaceShellProps){
  const {bootstrap,preferences,dashboard,nav,visiblePage,catalogPending,status,loading,error,refreshDisabled,loginOpen,notice,searchOpen,query,announcements,searchedModels,filteredActions,contentRef,children,setPage,refresh,retry,setQuery,setSearchOpen,setAnnouncements,setLoginOpen,clearNotice,selectSite,configureModel,windowControl,interfaceId}=props;
  const activeNav=nav.find(n=>n.id===visiblePage)!,site=preferences.sites.find(s=>s.id===preferences.activeSiteId) || preferences.sites[0],mac=bootstrap.platform==='darwin',shortcut=mac ? '⌘' : 'Ctrl';
  const theme=useDefaultTheme(preferences.theme);
  return <div data-interface={interfaceId} data-theme={theme} className={'desktop-shell platform-'+(bootstrap.platform || 'browser')}><header className="titlebar">{!mac && <div className="titlebar-brand" title={"Lumi v"+bootstrap.version}><Logo small/><strong>Lumi</strong><span>AI 工作空间</span></div>}<div className="breadcrumb"><span>我的空间</span><ChevronRight size={12}/><strong>{activeNav.label}</strong></div><div className="titlebar-actions"><button className="global-search" onClick={() => { setQuery(''); setSearchOpen(true); }}><Search size={15}/><span>搜索工作台</span><kbd>{shortcut} K</kbd></button><span className="header-divider"/><button className={`icon-button refresh-button ${loading ? 'spin' : ''}`} onClick={refresh} disabled={refreshDisabled} aria-label="刷新站点数据" title="刷新数据"><RefreshCw size={17}/></button><button className="icon-button notification-button" onClick={() => setAnnouncements(true)} aria-label="查看站点公告" title="站点公告"><Bell size={17}/>{dashboard?.status.announcements?.length ? <i/> : null}</button><button className="avatar" onClick={() => dashboard?.user ? setPage('settings') : setLoginOpen(true)} title="账户与设置" aria-label="账户设置">{(dashboard?.user?.display_name || dashboard?.user?.username || 'L').slice(0, 1).toUpperCase()}</button>{bootstrap.desktop && !mac && <div className="window-controls"><button aria-label="最小化" onClick={() => windowControl('minimize')}><Minus size={13}/></button><button aria-label="最大化或恢复" onClick={() => windowControl('maximize')}><Square size={11}/></button><button className="window-close" aria-label="关闭窗口" onClick={() => windowControl('close')}><X size={15}/></button></div>}</div></header>
    <aside className="sidebar surface"><div className="sidebar-navigation"><div className="brand-row"><Logo/><div><strong>Lumi<span>●</span></strong><p>你的 AI，尽在一处</p></div></div><div className="sidebar-divider"/><div className="sidebar-caption">WORKSPACE</div><nav aria-label="主导航">{nav.filter(n=>n.section==='workspace').map(n => <button key={n.id} className={`nav-item ${visiblePage === n.id ? 'active' : ''}`} onClick={() => setPage(n.id)}><n.icon size={18} strokeWidth={1.7}/><span>{n.label}</span>{visiblePage === n.id ? <span className="nav-active-dot"/> : n.id === 'models' && catalogPending ? <span className="nav-count" style={{background:'var(--orange-soft)',color:'var(--orange)'}} title={catalogPending+' 项模型目录变动未读'}>{catalogPending}</span> : n.id === 'models' && dashboard?.catalog.models.length ? <span className="nav-count">{dashboard.catalog.models.length}</span> : null}</button>)}</nav><div className="sidebar-caption tools-caption">DEVELOPER TOOLS</div><nav aria-label="工具导航">{nav.filter(n=>n.section==='tools').map(n => <button key={n.id} className={`nav-item ${visiblePage === n.id ? 'active' : ''}`} onClick={() => setPage(n.id)}><n.icon size={18} strokeWidth={1.7}/><span>{n.label}</span>{visiblePage === n.id && <span className="nav-active-dot"/>}</button>)}</nav></div><div className="sidebar-footer"><nav aria-label="设置导航">{nav.filter(n=>n.section==='settings').map(n=><button key={n.id} className={`nav-item settings-nav ${visiblePage===n.id ? 'active' : ''}`} onClick={()=>setPage(n.id)}><n.icon size={18} strokeWidth={1.7}/><span>{n.label}</span>{n.id==='settings' && <span className="nav-shortcut">{shortcut} ,</span>}</button>)}</nav><div className="sidebar-divider"/><UpdateNotice/><div className="sidebar-site"><div className="site-icon"><Globe2 size={19}/></div><div><Select label="切换当前站点" className="site-switch" value={preferences.activeSiteId} onChange={selectSite}>{preferences.sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></div></div><div className="sidebar-status"><span className={`tiny-dot ${error ? 'red' : !dashboard?.user ? 'amber' : ''}`}/>{status}<span>v{bootstrap.version}</span></div></div></aside>
    <main className="main-area">
      <div className="content-scroll" ref={contentRef}><div className="content-container">{error && <div className="warning-banner error-banner"><AlertCircle size={16}/><span>{error}</span><button onClick={retry}>重试</button></div>}{dashboard?.warnings.length ? <details className="sync-warnings"><summary><AlertCircle size={14}/>{dashboard.warnings.length} 项数据未能同步，点击查看</summary>{dashboard.warnings.map((w, i) => <p key={i}>{w}</p>)}</details> : null}
        {children}
      </div></div>
    </main>
    {loginOpen && <LoginModal key={preferences.activeSiteId} onClose={() => setLoginOpen(false)}/>}
    {notice && <div className={`toast ${notice.kind}`} role="status" key={notice.id}>{notice.kind === 'success' ? <CheckCircle2 size={19}/> : notice.kind === 'error' ? <AlertCircle size={19}/> : <Info size={19}/>}<span>{notice.text}</span><button onClick={clearNotice} aria-label="关闭通知"><X size={15}/></button></div>}
    {searchOpen && <Modal title="随时找到你需要的" subtitle="搜索页面、模型或开发工具" onClose={() => setSearchOpen(false)}><div className="search-input command-search"><Search size={18}/><input placeholder="搜索工作台…" aria-label="搜索工作台内容" autoFocus value={query} onChange={e => setQuery(e.target.value)}/><kbd>ESC</kbd></div><div className="command-results">{filteredActions.map(n => <button key={n.id} onClick={() => { setPage(n.id); setSearchOpen(false); }}><n.icon size={18}/><div><strong>{n.label}</strong><span>{n.hint}</span></div><ChevronRight size={15}/></button>)}{searchedModels.map(m => <button key={m.model_name} onClick={() => { if (m.supported_endpoint_types.some(p => p.includes('anthropic'))) configureModel(m.model_name, 'claude'); else configureModel(m.model_name, 'codex'); setSearchOpen(false); }}><Boxes size={18}/><div><strong>{m.model_name}</strong><span>{m.vendor} · 模型配置</span></div><ArrowUpRight size={15}/></button>)}{!filteredActions.length && !searchedModels.length && <p className="empty-search">没有找到结果，试试“模型”或“Codex”。</p>}</div></Modal>}
    {announcements && <Modal title="站点公告" subtitle={site.name} onClose={() => setAnnouncements(false)}><div className="announcement-list">{dashboard?.status.announcements?.length ? dashboard.status.announcements.map((a, i) => <article key={i}><div><Pill tone="green">站点消息</Pill><span>{new Date(a.publishDate).toLocaleDateString()}</span></div><p>{a.content}</p></article>) : <div className="empty-state"><Bell size={25}/><h3>暂无公告</h3><p>站点发布的新消息会显示在这里。</p></div>}</div></Modal>}
  </div>;
}
