import { useState,useEffect,useRef } from 'react';
import { Plus, Globe2, Check, ExternalLink, KeyRound, ShieldCheck, Monitor, Sun, Moon, Laptop, ChevronRight, Info, Trash2, Save, Server, Paintbrush, Bell, ArrowUpRight, RefreshCw, LogIn, LogOut } from 'lucide-react';
import { useApp } from '../context';
import { bridge } from '../bridge';
import { Button, PageIntro, SectionHeading, Select, Pill, Modal, Logo } from '../components/ui';
import {UpdateNotice} from '../components/UpdateNotice';
import RuntimeLogs from '../components/RuntimeLogs';
import BarSettings from '../components/BarSettings';
import {MotionSwap} from '../components/MotionSwap';
import type { SiteProfile, SiteInput, Theme } from '../../shared/types';
export default function Settings() {
  const { preferences, bootstrap, updatePreferences, setPreferences, reloadBootstrap, refresh, toast,openLogin } = useApp();
  const [view,setView]=useState<'general'|'bar'|'logs'>('general');
  const root=useRef<HTMLDivElement>(null);
  useEffect(()=>{root.current?.closest('.content-scroll')?.scrollTo({top:0});},[view]);
  const [edit, setEdit] = useState<SiteProfile | 'new' | null>(null); const [remove, setRemove] = useState<SiteProfile | null>(null);
  const [form, setForm] = useState<SiteInput>({ name: '', url: '', allowHttp: false }); const [busy, setBusy] = useState(false);
  const [threshold, setThreshold] = useState(String(preferences.lowBalanceThreshold));
  function openEdit(site: SiteProfile | 'new') { setEdit(site); setForm(site === 'new' ? { name: '', url: 'https://', allowHttp: false, accessToken: '', apiKey: '' } : { id: site.id, name: site.name, url: site.url, userId: site.userId, allowHttp: site.allowHttp, accessToken: '', apiKey: '' }); }
  const patch = <K extends keyof SiteInput>(key: K, value: SiteInput[K]) => setForm(f => ({ ...f, [key]: value }));
  async function saveSite(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { const p = await bridge.saveSite(form); setPreferences(p); setEdit(null); setForm({ name: '', url: '', allowHttp: false }); await reloadBootstrap(); toast('站点设置已保存。', 'success'); } catch (e: any) { toast(e.message, 'error'); } finally { setBusy(false); } }
  async function removeSite() { if (!remove) return; setBusy(true); try { setPreferences(await bridge.removeSite(remove.id)); setRemove(null); await reloadBootstrap(); toast('站点已移除。', 'success'); } catch (e: any) { toast(e.message, 'error'); } finally { setBusy(false); } }
  async function preference(patch: Parameters<typeof updatePreferences>[0]) { try { await updatePreferences(patch); toast('设置已更新', 'success'); } catch (e: any) { toast(e.message, 'error'); } }
  return <div className="page settings-page" ref={root}><PageIntro title="属于你的工作台" description="连接你的站点，调整外观和同步偏好。"/><nav className="settings-subnav" aria-label="设置二级菜单"><button className={view==='general' ? 'active' : ''} aria-current={view==='general' ? 'page' : undefined} onClick={()=>setView('general')}>常规设置</button><button className={view==='bar' ? 'active' : ''} aria-current={view==='bar' ? 'page' : undefined} onClick={()=>setView('bar')}>菜单栏与托盘</button><button className={view==='logs' ? 'active' : ''} aria-current={view==='logs' ? 'page' : undefined} onClick={()=>setView('logs')}>实时日志</button></nav><MotionSwap identity={view}>{view==='logs' ? <RuntimeLogs/> : view==='bar' ? <BarSettings/> : <div className="settings-general">
    <section className="surface panel"><SectionHeading title="站点连接" sub="支持任意兼容 New API 的站点地址" action={<Button onClick={() => openEdit('new')}><Plus size={15}/>添加站点</Button>}/><div className="site-list">{preferences.sites.map(s => <div className={`site-row ${s.id === preferences.activeSiteId ? 'selected' : ''}`} key={s.id}><div className="site-avatar"><Globe2 size={22}/></div><div className="site-row-info"><strong>{s.name}{s.id === preferences.activeSiteId && <Pill tone="green">当前站点</Pill>}</strong><span>{s.url}</span><div><span><span className={`tiny-dot ${s.accessTokenConfigured ? '' : 'grey'}`}/>{s.accessTokenConfigured ? s.username ? '已登录 · '+s.username : '账户凭据已保存' : '尚未登录'}</span>{s.apiKeyConfigured && <span><KeyRound size={11}/>API Key 已保存</span>}</div></div><div className="site-row-actions">{s.id === preferences.activeSiteId && (s.accessTokenConfigured ? <Button onClick={async () => {try {setPreferences(await bridge.logout(s.id));await reloadBootstrap();await refresh();toast('已退出并清除本机登录凭证。','success');}catch(e:any){toast(e.message,'error');}}}><LogOut size={15}/>退出登录</Button> : <Button variant="primary" onClick={openLogin}><LogIn size={15}/>登录</Button>)}{s.id !== preferences.activeSiteId && <Button onClick={() => preference({ activeSiteId: s.id })}>切换</Button>}<Button onClick={() => openEdit(s)}>编辑</Button><button className="icon-button" aria-label={`在浏览器中打开 ${s.name}`} onClick={() => bridge.openExternal(s.url).catch(e => toast(e.message, 'error'))}><ExternalLink size={16}/></button>{preferences.sites.length > 1 && <button className="icon-button danger-icon" aria-label={`移除 ${s.name}`} onClick={() => setRemove(s)}><Trash2 size={16}/></button>}</div></div>)}</div><div className="info-note"><KeyRound size={15}/><span>通过账号密码登录自动获取账户凭证并保存。工具配置会自动使用专用 API 令牌，无需复制密钥。</span></div></section>
    <div className="settings-two-columns"><section className="surface panel"><SectionHeading title="外观" sub="简洁、清晰，专注你的工作"/><div className="theme-options">{([['light', Sun, '浅色'], ['dark', Moon, '深色'], ['system', Laptop, '跟随系统']] as const).map(([theme, Icon, label]) => <button key={theme} className={preferences.theme === theme ? 'active' : ''} onClick={() => preference({ theme })}><div className={`theme-preview ${theme}`}><i/><span/><span/></div><span><Icon size={14}/>{label}{preferences.theme === theme && <Check size={13}/>}</span></button>)}</div></section><section className="surface panel"><SectionHeading title="同步与提醒" sub="按你的节奏更新数据"/><div className="setting-control"><div><strong>自动刷新</strong><p>所有页面按此频率刷新，仅在窗口可见时执行；接口缓存与请求合并继续生效</p></div><Select tone="blue" label="自动刷新频率" value={preferences.refreshInterval} onChange={v => preference({ refreshInterval: Number(v) })}><option value="0">关闭</option><option value="30">30 秒</option><option value="60">1 分钟</option><option value="120">2 分钟</option><option value="300">5 分钟</option><option value="600">10 分钟</option><option value="1800">30 分钟</option><option value="3600">1 小时</option></Select></div><div className="setting-control balance-threshold"><div><strong>余额提醒阈值</strong><p>低于此额度时显示桌面通知</p></div><div><input aria-label="余额提醒阈值" type="number" min="0" step="0.1" value={threshold} onChange={e => setThreshold(e.target.value)} className="text-input"/><button className="icon-button" aria-label="保存提醒阈值" onClick={() => Number.isFinite(Number(threshold)) && Number(threshold) >= 0 ? preference({ lowBalanceThreshold: Number(threshold) }) : toast('请输入有效提醒阈值。', 'error')}><Check size={17}/></button></div></div></section></div>
    <section className="surface panel"><SectionHeading title="工具专用令牌" sub="工具配置会自动复用或创建对应渠道的专用密钥"/><div className="setting-control"><div><strong>默认名称前缀</strong><p>例如 Lumi-Codex · 可按你的工作习惯调整</p></div><form className="token-prefix-form" onSubmit={e => {e.preventDefault();const value=new FormData(e.currentTarget).get('prefix') as string;if (!/^[a-zA-Z0-9_-]{1,20}$/.test(value)) return toast('前缀限 1–20 个英文字母、数字、短横线或下划线。','error');void preference({tokenPrefix:value});}}><input className="text-input" name="prefix" aria-label="专用令牌名称前缀" key={preferences.tokenPrefix} defaultValue={preferences.tokenPrefix} maxLength={20}/><Button type="submit"><Check size={15}/>保存</Button></form></div></section>
    <UpdateNotice placement="settings"/>
    <section className="surface panel about-panel"><Logo/><div><h3>Lumi <Pill tone="muted">v{bootstrap.version}</Pill></h3><p>你的 AI，尽在一处。基于 Electron 的 New API 专属工作台。</p><span>{bootstrap.desktop ? 'Electron 桌面运行中' : '浏览器预览'} · {bootstrap.secureStorage ? '系统加密存储可用' : bootstrap.desktop ? '系统加密存储不可用' : '密钥配置仅支持桌面应用'}</span></div><div><Button onClick={() => bridge.openExternal('https://docs.newapi.ai/zh/docs/api').catch(e => toast(e.message, 'error'))}>New API 文档<ArrowUpRight size={13}/></Button><Button onClick={() => bridge.openExternal('https://github.com/farion1231/cc-switch').catch(e => toast(e.message, 'error'))}>CC Switch<ArrowUpRight size={13}/></Button></div></section>
    {edit && <Modal title={edit === 'new' ? '添加站点' : '编辑站点'} subtitle="先保存站点地址，再使用账号密码登录" onClose={() => { if (!busy) { setEdit(null); setForm({ name: '', url: '', allowHttp: false }); } }}><form onSubmit={saveSite}><div className="form-two-columns"><div><label className="field-label">站点名称</label><input aria-label="站点名称" className="text-input" value={form.name} onChange={e => patch('name', e.target.value)} placeholder="我的 AI 站点" required maxLength={80}/></div><div><label className="field-label">用户 ID<span>旧版鉴权可选</span></label><input aria-label="用户 ID" className="text-input" value={form.userId || ''} onChange={e => patch('userId', e.target.value ? Number(e.target.value) : undefined)} type="number" min="1" placeholder="例如 100"/></div></div><label className="field-label">站点地址<span>无需 /v1 或 /api</span></label><input aria-label="站点地址" className="text-input mono" type="url" required value={form.url} onChange={e => patch('url', e.target.value)} placeholder="https://api.example.com"/><details className="advanced-credentials"><summary>高级：手动账户凭证</summary><label className="field-label">账户访问令牌<span>在站点“个人设置”中生成</span></label><input aria-label="账户访问令牌" className="text-input mono" type="password" autoComplete="off" value={form.accessToken || ''} onChange={e => patch('accessToken', e.target.value)} placeholder={edit !== 'new' && edit.accessTokenConfigured ? '已保存 · 留空保持原值' : '用于余额、账单和模型查询'}/><label className="field-label">模型 API Key<span>可选 · 默认工具密钥</span></label><input aria-label="站点 API Key" className="text-input mono" type="password" autoComplete="off" value={form.apiKey || ''} onChange={e => patch('apiKey', e.target.value)} placeholder={edit !== 'new' && edit.apiKeyConfigured ? '已保存 · 留空保持原值' : 'sk-…'}/>{edit !== 'new' && (edit.accessTokenConfigured || edit.apiKeyConfigured) && <div className="form-two-columns">{edit.accessTokenConfigured && <label className="checkbox-label"><input type="checkbox" checked={!!form.clearAccessToken} onChange={e => patch('clearAccessToken', e.target.checked)}/>清除账户访问令牌</label>}{edit.apiKeyConfigured && <label className="checkbox-label"><input type="checkbox" checked={!!form.clearApiKey} onChange={e => patch('clearApiKey', e.target.checked)}/>清除默认 API Key</label>}</div>}</details>{form.url.startsWith('http:') && <div className="http-permission"><label className="checkbox-label"><input type="checkbox" checked={form.allowHttp} onChange={e => patch('allowHttp', e.target.checked)}/>允许通过此 HTTP 站点发送凭据</label><p>当前地址没有 HTTPS 加密；账户令牌和 API Key 会通过明文连接传输。</p></div>}{edit !== 'new' && edit.url !== form.url && <div className="warning-banner"><Info size={14}/>更改站点地址会清除该站点原有凭据，请重新输入。</div>}{!bootstrap.desktop && <div className="info-note"><Monitor size={15}/><span>浏览器模式可保存站点外观设置；输入凭据和连接真实接口需要 Electron 桌面应用。</span></div>}<div className="modal-actions"><Button type="button" disabled={busy} onClick={() => setEdit(null)}>取消</Button><Button type="submit" variant="primary" busy={busy}><Save size={15}/>保存站点</Button></div></form></Modal>}
    {remove && <Modal title="移除站点" subtitle={remove.name} onClose={() => setRemove(null)}><p className="modal-text">此操作会移除站点设置与本机保存的访问凭据。站点账户仍可正常使用。</p><div className="modal-actions"><Button onClick={() => setRemove(null)}>取消</Button><Button variant="danger" busy={busy} onClick={removeSite}>确认移除</Button></div></Modal>}
  </div>}</MotionSwap></div>;
}
