import { ComposedChart, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { compact } from '../../shared/utils';
const COLORS = ['#6e978a', '#9b90c5', '#83a8c6', '#c4a782', '#adbb86', '#93a4b3'];
export interface ChartLine { id: string; name: string; color: string; }
export interface ChartRow { tooltipLabel?: string; label: string; cost: number; tokens: number; requests: number; values?: Record<string,number>; }
export function TrendChart({data,metric='cost',symbol='',series=[]}:{data:ChartRow[];metric?:'cost'|'tokens'|'requests';symbol?:string;series?:ChartLine[]}) {
  const metricName=metric==='cost' ? '消费金额' : metric==='tokens' ? 'Tokens' : '请求次数';
  return <div className="trend-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:14,right:10,left:-14,bottom:0}}>
    <CartesianGrid stroke="var(--chart-grid)" strokeDasharray="3 6" vertical={false}/>
    <XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'var(--text-muted)'}} dy={10} minTickGap={25} interval="preserveStartEnd"/>
    <YAxis axisLine={false} tickLine={false} tick={{fontSize:11,fill:'var(--text-muted)'}} tickFormatter={v=>metric==='cost' ? `${symbol}${v}` : compact(v)} width={64} tickCount={4}/>
    <Tooltip cursor={{stroke:'#89a898',strokeDasharray:'3 4'}} contentStyle={{background:'var(--tooltip-bg)',border:'1px solid var(--border)',borderRadius:12,boxShadow:'none',fontSize:12,color:'var(--text)'}} itemStyle={{color:'var(--text)'}} formatter={(v:any,name:any)=>[metric==='cost' ? `${symbol}${Number(v).toFixed(3)}` : compact(Number(v)),series.length ? name : metricName]} labelFormatter={(label,payload)=>payload?.[0]?.payload?.tooltipLabel || label} labelStyle={{color:'var(--text-muted)',marginBottom:6}}/>
    {series.length ? series.map(line=><Line key={line.id} name={line.name} type="monotone" dataKey={(row:ChartRow)=>row.values?.[line.id] ?? 0} stroke={line.color} strokeWidth={2} dot={data.length===1 ? {r:4} : false} activeDot={{r:4,stroke:'var(--panel)',strokeWidth:2}} animationDuration={350}/>) : <Area name={metricName} type="monotone" dataKey={metric} stroke="#6e9687" strokeWidth={2.5} fill="var(--chart-fill)" dot={data.length===1 ? {r:4,fill:'#6e9687'} : false} activeDot={{r:5,fill:'#6e9687',stroke:'var(--panel)',strokeWidth:3}} animationDuration={350}/>}
  </ComposedChart></ResponsiveContainer></div>;
}
export function ModelDonut({ data, total, symbol }: { data: { name: string; value: number }[]; total: string; symbol: string }) {
  return <><div className="donut-wrap"><ResponsiveContainer width="100%" height={166}><PieChart><Pie data={data} dataKey="value" innerRadius={59} outerRadius={74} paddingAngle={data.length > 1 ? 1 : 0} minAngle={Math.max(0, Math.min(5, 360 / data.length - 1))} cornerRadius={2} stroke="none" startAngle={90} endAngle={-270}>{data.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]}/>)}</Pie><Tooltip contentStyle={{ background: 'var(--tooltip-bg)', border: '1px solid var(--border)', borderRadius: 12, fontSize: 12 }} formatter={(v: any) => `${symbol}${Number(v).toFixed(2)}`}/></PieChart></ResponsiveContainer><div className="donut-label"><span>区间总消耗</span><strong>{total}</strong></div></div><div className="model-legend">{data.slice(0, 3).map((m, i) => <div key={m.name}><span className="legend-dot" style={{ background: COLORS[i] }}/><span className="legend-name" title={m.name}>{m.name}</span><span>{data.reduce((s, d) => s + d.value, 0) ? Math.round(m.value / data.reduce((s, d) => s + d.value, 0) * 100) : 0}%</span></div>)}</div></>;
}
