import {useEffect,useState,type FormEvent} from 'react';
import {ArrowRight,Globe2,KeyRound,ShieldCheck,LogIn} from 'lucide-react';
import {useApp} from '../context';
import {bridge} from '../bridge';
import {Button,Modal,Pill,Logo} from './ui';
import type {LoginInfo,LoginResult} from '../../shared/types';
export function LoginModal({onClose}:{onClose():void}) {
  const {preferences,bootstrap,setPreferences,reloadBootstrap,refresh,toast}=useApp();
  const site=preferences.sites.find(s => s.id === preferences.activeSiteId)!;
  const [info,setInfo]=useState<LoginInfo | null>(null);const [error,setError]=useState('');const [username,setUsername]=useState(site.username || '');const [password,setPassword]=useState('');const [code,setCode]=useState('');const [challenge,setChallenge]=useState<Extract<LoginResult,{state:'verification'}> | null>(null);const [busy,setBusy]=useState(false);
  useEffect(() => {let live=true;bridge.loginInfo().then(v => {if (live) setInfo(v);}).catch(e => {if (live) setError(e.message);});return () => {live=false;};},[site.id]);
  async function success(p:typeof preferences) {setPreferences(p);setPassword('');await reloadBootstrap();await refresh();toast('登录成功，凭证已由系统加密保存。','success');onClose();}
  async function submit(e:FormEvent) {e.preventDefault();setBusy(true);setError('');try {const result=challenge ? await bridge.verifyLogin({challengeId:challenge.challengeId,code}) : await bridge.login({username,password});setPassword('');if (result.state === 'success') await success(result.preferences);else setChallenge(result);} catch(e:any) {setError(e.message);}finally {setBusy(false);}}
  async function secureLogin() {setBusy(true);setError('');setPassword('');try {await success(await bridge.browserLogin());}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <Modal title={challenge ? '完成账户验证' : '登录你的 AI 站点'} subtitle={site.name+' · '+site.url} onClose={() => {if (!busy) onClose();}}><div className="login-trust"><ShieldCheck size={20}/><div><strong>登录一次，下次自动连接</strong><span>仅保存加密凭证，账号密码不写入磁盘。</span></div></div>{!bootstrap.desktop && <div className="warning-banner"><Globe2 size={17}/><span>请在 Lumi 桌面应用中登录，浏览器仅显示站点公开信息。</span></div>}{site.url.startsWith('http:') && !site.allowHttp && <div className="warning-banner"><span>此站点为 HTTP，请先编辑站点并勾选允许 HTTP 连接。</span></div>}{error && <p className="login-error" role="alert">{error}</p>}{info?.turnstile && !challenge ? <div className="secure-login"><div className="secure-login-icon"><Globe2 size={30}/></div><h3>在站点安全窗口中输入账号密码</h3><p>此站点已启用人机验证。登录和验证成功后，Lumi 会自动获取凭证、保存并关闭窗口。</p><Button variant="primary" busy={busy} disabled={!bootstrap.desktop || !site.allowHttp && site.url.startsWith('http:')} onClick={secureLogin}><LogIn size={16}/>打开安全登录窗口<ArrowRight size={15}/></Button></div> : <form onSubmit={submit}>{challenge ? <><label className="field-label">验证器代码或备用码</label><input aria-label="两步验证码" className="text-input mono" autoComplete="one-time-code" value={code} onChange={e => setCode(e.target.value)} required maxLength={128}/><p className="field-help">验证步骤在 {new Date(challenge.expiresAt).toLocaleTimeString()} 过期。</p></> : <><label className="field-label">账号</label><input aria-label="登录账号" className="text-input" autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} required maxLength={100}/><label className="field-label">密码</label><input aria-label="登录密码" className="text-input" type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required maxLength={1024}/></>}<div className="modal-actions"><Button type="button" onClick={onClose} disabled={busy}>取消</Button><Button variant="primary" type="submit" busy={busy} disabled={!bootstrap.desktop || !info || info.enabled === false || !site.allowHttp && site.url.startsWith('http:')}><KeyRound size={15}/>{challenge ? '验证并登录' : '登录并保存'}</Button></div>{info?.enabled === false && <p className="field-help">站点关闭了账号密码登录，请使用安全登录窗口。</p>}</form>}{(!info?.turnstile || challenge) && <button className="text-link full-width" disabled={busy || !bootstrap.desktop || !site.allowHttp && site.url.startsWith('http:')} onClick={secureLogin}>使用站点安全登录窗口<ArrowRight size={13}/></button>}</Modal>;
}
export function Welcome({onLogin}:{onLogin():void}) {
  const {preferences,setPage,dashboard}=useApp();const site=preferences.sites.find(s => s.id === preferences.activeSiteId)!;
  return <div className="welcome-page"><section className="surface welcome-hero"><Pill tone="green">LUMI · YOUR AI WORKSPACE</Pill><div className="welcome-logo"><Logo/></div><h1>你的 AI，<br/><em>清晰可见。</em></h1><p>余额、每一笔消耗，以及你的开发工具。<br/>登录 {site.name}，让一切各就其位。</p><div className="welcome-actions"><Button variant="primary" onClick={onLogin}><LogIn size={17}/>账号密码登录<ArrowRight size={16}/></Button><Button onClick={() => setPage('settings')}><Globe2 size={16}/>管理站点</Button></div><div className="welcome-address"><span className="tiny-dot"/>{site.url}<Pill tone="muted">{dashboard?.status.version || 'New API'}</Pill></div></section><div className="welcome-features">{[['01','每一份消耗','真实余额、用量曲线和详细账单'],['02','每一个模型','渠道倍率、缓存单价和计费规则'],['03','每一次创造','Codex / Claude Code 自动配钥']].map(([n,title,desc]) => <div className="surface" key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></div>;
}
