import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './workbench.css';
import './select.css';
import './theme-tokens.css';
import './theme.css';
import './updates-trends.css';
import './filters-tools-motion.css';
import './platform-logs.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
