import {PopupPresence} from '../../../src/components/PopupPresence';
import { useEffect,useState,useRef } from 'react';
import { Plus, KeyRound, ShieldCheck, Eye, Pause, Play, Info, ArrowUpRight, Check, Copy, Loader2 } from 'lucide-react';
import { useApp } from '../../../src/context';
import { bridge } from '../../../src/bridge';
import { Button, PageIntro, SectionHeading, Pill, ToolIcon, Modal, Select, Empty } from '../../../src/components/ui';
import { compact, currency, formatMoney } from '../../../shared/utils';
import { RouteDetails } from '../../../src/components/Pricing';
import {TokenEditor} from './TokenEditor';
import {Welcome} from '../../../src/components/Login';
import {useSavedSelection} from '../../../src/selections';
import { availableGroups,groupLabel,groupRatio } from '../../../shared/catalog';
import type { Tool, ApiToken } from '../../../shared/types';
export default function Tokens() {
  const { dashboard: d, preferences, refresh, reloadBootstrap, toast, setPage,openLogin } = useApp();
  const [creating, setCreating] = useState(false); const [name, setName] = useState('Lumi-Codex'); const [tool, setTool] = useSavedSelection<Tool | ''>('tokens.tool','codex',v=>['codex','claude',''].includes(v));
  const [group, setGroup] = useSavedSelection<string>('tokens.group',''); const [unlimited, setUnlimited] = useState(false); const [quota, setQuota] = useState('50'); const [models, setModels] = useState('');
  const [busy, setBusy] = useState(false); const [toggle, setToggle] = useState<ApiToken | null>(null);
  const [editing,setEditing]=useState<ApiToken|null>(null);
  const [revealed,setRevealed]=useState<{token:ApiToken;key:string;busy:boolean}|null>(null),[copying,setCopying]=useState<number|null>(null),keyRequest=useRef(0);
  useEffect(()=>{setCreating(false);setEditing(null);setToggle(null);setRevealed(null);keyRequest.current++;return()=>{keyRequest.current++;};},[preferences.activeSiteId,d?.user?.id]);
  if (!d?.user) return <Welcome onLogin={openLogin}/>; const c = currency(d.status);
  const bindings = preferences.bindings.filter(b => b.siteId === preferences.activeSiteId);
  function openCreate() { setName(preferences.tokenPrefix+(tool==='codex' ? 'Codex' : tool==='claude' ? 'Claude' : 'API')); if(!Object.keys(d!.catalog.usableGroups).includes(group))setGroup(Object.keys(d!.catalog.usableGroups).find(g => g !== 'auto') || Object.keys(d!.catalog.usableGroups)[0] || ''); setCreating(true); }
  async function reveal(token:ApiToken){const request=++keyRequest.current;setRevealed({token,key:'',busy:true});try{const key=await bridge.getTokenKey(token.id);if(request===keyRequest.current)setRevealed({token,key,busy:false});}catch(e:any){if(request===keyRequest.current){setRevealed(null);toast(e.message,'error');}}}
  async function copy(token:ApiToken){setCopying(token.id);try{await bridge.copyTokenKey(token.id);toast('API 密钥已复制。','success');}catch(e:any){toast(e.message,'error');}finally{setCopying(null);}}
  async function create(e: React.FormEvent) { e.preventDefault(); if (!unlimited && (!Number.isFinite(Number(quota)) || Number(quota) < 0)) return toast('请输入有效额度。', 'error'); setBusy(true); try { await bridge.createToken({ name, tool: tool || undefined, group, unlimited, quota: Number(quota) / c.rate * c.unit, models: models || undefined }); setCreating(false); await reloadBootstrap(); await refresh(); toast(tool ? '令牌已创建并绑定，前往工具配置预览并应用。' : '令牌已创建。', 'success'); } catch (e: any) { toast(e.message, 'error'); await refresh(); } finally { setBusy(false); } }
  async function toggleStatus() { if (!toggle) return; setBusy(true); try { await bridge.toggleToken(toggle.id, toggle.status !== 1); setToggle(null); await refresh(); toast('令牌状态已更新。', 'success'); } catch (e: any) { toast(e.message, 'error'); } finally { setBusy(false); } }
  return <div className="page"><PageIntro title="为每个工具，留一把专属钥匙" description="管理站点令牌与额度，清楚区分每个开发工具的消耗。" action={<Button variant="primary" onClick={openCreate} disabled={!d.user}><Plus size={16}/>创建令牌</Button>}/>
    <div className="token-overview"><div className="surface token-overview-card"><KeyRound size={22}/><strong>{d.tokens.length}</strong><span>API 令牌</span></div><div className="surface token-overview-card"><ShieldCheck size={22}/><strong>{d.tokens.filter(t => t.status === 1).length}</strong><span>正在启用</span></div><div className="surface token-overview-card"><Eye size={22}/><strong>系统加密</strong><span>密钥按需查看或复制</span></div></div>
    <section className="surface panel"><SectionHeading title="我的 API 令牌" sub="余额与累计消费按令牌统计" action={<button className="text-link" onClick={() => setPage('tools')}>管理工具绑定<ArrowUpRight size={14}/></button>}/>{d.tokens.length ? <div className="table-scroll"><table className="data-table token-table"><thead><tr><th>名称 / 工具</th><th>状态</th><th>渠道 / 倍率</th><th>剩余额度</th><th>累计消耗</th><th>有效期</th><th>操作</th></tr></thead><tbody>{d.tokens.map(t => { const b = bindings.find(x => x.tokenName === t.name) || preferences.managedTokens.find(x => x.siteId === preferences.activeSiteId && x.id === t.id); const ratio = !t.unlimited_quota && t.used_quota + t.remain_quota > 0 ? t.used_quota / (t.used_quota + t.remain_quota) * 100 : 0; return <tr key={t.id}><td><div className="model-cell">{b ? <ToolIcon tool={b.tool} size={34}/> : <div className="generic-key-icon"><KeyRound size={17}/></div>}<div><strong>{t.name}</strong><span>{b ? b.tool === 'codex' ? '已绑定 Codex' : '已绑定 Claude Code' : `令牌 #${t.id}`}</span></div></div></td><td><Pill tone={t.status === 1 ? 'green' : t.status === 2 ? 'muted' : 'orange'}>{t.status === 1 ? '启用' : t.status === 2 ? '停用' : t.status === 3 ? '已过期' : '额度耗尽'}</Pill></td><td><span className="token-channel">{d.catalog.usableGroups[t.group] || t.group || 'default'}<strong>{groupRatio(d.catalog,t.group)===undefined ? '浮动' : '×'+groupRatio(d.catalog,t.group)}</strong></span></td><td>{t.unlimited_quota ? <span>无限额</span> : <div className="quota-cell"><strong>{formatMoney(t.remain_quota, d.status)}</strong><div><i style={{ width: `${Math.min(100, ratio)}%` }}/></div></div>}</td><td>{formatMoney(t.used_quota, d.status)}</td><td className="muted">{t.expired_time <= 0 ? '长期有效' : new Date(t.expired_time * 1000).toLocaleDateString()}</td><td><div className="token-row-controls"><Button variant="ghost" aria-label={'查看令牌 '+t.name} disabled={!d.user} onClick={()=>reveal(t)}><Eye size={14}/>查看</Button><Button variant="ghost" aria-label={'复制令牌 '+t.name} disabled={!d.user} busy={copying===t.id} onClick={()=>copy(t)}><Copy size={14}/>复制</Button><Button variant="ghost" aria-label={'控制令牌 '+t.name} disabled={!d.user} onClick={()=>setEditing(t)}>控制</Button><Button variant="ghost" disabled={!d.user} onClick={() => setToggle(t)}>{t.status === 1 ? <Pause size={14}/> : <Play size={14}/>} {t.status === 1 ? '停用' : '启用'}</Button></div></td></tr>; })}</tbody></table></div> : <Empty title="还没有 API 令牌" description="连接账户后，可以为 Codex 和 Claude Code 创建独立令牌。" action={<Button onClick={openCreate}><Plus size={15}/>创建令牌</Button>}/>}</section>
    <div className="surface token-help"><ToolIcon tool="codex" size={35}/><ToolIcon tool="claude" size={35}/><div><h3>独立令牌，让账单更清楚</h3><p>创建时选择对应工具，Lumi 会保存密钥并绑定令牌名称。进入工具配置页预览并应用，即可查看各工具的独立消费。</p></div><Button onClick={() => setPage('tools')}>配置工具<ArrowRightIcon/></Button></div>
    <div className="info-note"><Info size={15}/><span>创建令牌只分配 API 访问额度，不会充值账户。停用后该令牌将无法调用模型。工具仍运行时，请留意令牌状态。</span></div>
    <PopupPresence>{creating && <Modal title="创建 API 令牌" subtitle="创建专用令牌并绑定到开发工具。" onClose={() => { if (!busy) setCreating(false); }}><form onSubmit={create}><label className="field-label">令牌名称</label><input className="text-input" required value={name} onChange={e => setName(e.target.value)} maxLength={50}/><div className="form-two-columns"><div><label className="field-label">绑定工具</label><Select label="绑定工具" value={tool} onChange={v => { setTool(v as Tool | ''); setName(preferences.tokenPrefix+(v === 'codex' ? 'Codex' : v === 'claude' ? 'Claude' : 'API')); }}><option value="codex">Codex</option><option value="claude">Claude Code</option><option value="">不绑定工具</option></Select></div><div><label className="field-label">分组</label><Select label="令牌分组" value={group} onChange={v => {setGroup(v);setModels('');}}>{Object.keys(d.catalog.usableGroups).length ? Object.entries(d.catalog.usableGroups).map(([id, n]) => <option key={id} value={id}>{groupLabel(d.catalog,id)}</option>) : <option value={group}>{group}</option>}</Select></div></div><label className="field-label">使用额度 {c.symbol && `(${c.symbol})`}</label><input className="text-input" type="number" step="0.01" min="0" required={!unlimited} disabled={unlimited} value={quota} onChange={e => setQuota(e.target.value)}/><label className="checkbox-label"><input type="checkbox" checked={unlimited} onChange={e => setUnlimited(e.target.checked)}/>不限制令牌额度（仍受账户余额限制）</label><RouteDetails catalog={d.catalog} status={d.status} group={group}/><label className="field-label">限制模型<span>留空允许该渠道所有模型</span></label><div className="token-model-choices">{d.catalog.models.filter(m => availableGroups(m,d.catalog).includes(group)).map(m => {const chosen=models.split(',').filter(Boolean);const selected=chosen.includes(m.model_name);return <button type="button" className={'model-choice '+(selected ? 'selected' : '')} key={m.model_name} onClick={() => setModels(selected ? chosen.filter(x => x !== m.model_name).join(',') : [...chosen,m.model_name].join(','))}>{selected && <Check size={11}/>} {m.model_name}</button>;})}</div><p className="field-help">已选 {models.split(',').filter(Boolean).length} 个模型 · 倍率作用于模型价格，不改变分配给令牌的总额度。</p><div className="modal-actions"><Button type="button" onClick={() => setCreating(false)}>取消</Button><Button type="submit" variant="primary" busy={busy} disabled={!d.user || !group}><Plus size={15}/>创建{tool ? '并绑定' : ''}</Button></div></form></Modal>}</PopupPresence>
    <PopupPresence>{editing && <TokenEditor key={editing.id} token={editing} onClose={()=>setEditing(null)}/>}</PopupPresence>
    <PopupPresence>{revealed && <Modal title="查看 API 密钥" subtitle={revealed.token.name} className="token-key-modal" onClose={()=>{keyRequest.current++;setRevealed(null);}}>{revealed.busy ? <p className="field-help"><Loader2 size={16} className="spin"/>正在读取密钥…</p> : <code className="token-key-value">{revealed.key}</code>}<div className="modal-actions"><Button type="button" onClick={()=>{keyRequest.current++;setRevealed(null);}}>关闭</Button><Button type="button" variant="primary" busy={copying===revealed.token.id} disabled={revealed.busy} onClick={()=>copy(revealed.token)}><Copy size={15}/>复制密钥</Button></div></Modal>}</PopupPresence>
    <PopupPresence>{toggle && <Modal title={`${toggle.status === 1 ? '停用' : '启用'} API 令牌`} subtitle={toggle.name} onClose={() => { if (!busy) setToggle(null); }}><div className="info-note"><Info size={16}/><span>{toggle.status === 1 ? '停用后，使用此令牌的工具将无法继续调用模型。可随时重新启用。' : '启用后，此令牌可以重新发起请求，前提是余额与有效期满足站点要求。'}</span></div><div className="modal-actions"><Button onClick={() => setToggle(null)}>取消</Button><Button variant={toggle.status === 1 ? 'danger' : 'primary'} busy={busy} disabled={!d.user} onClick={toggleStatus}>{toggle.status === 1 ? '确认停用' : '确认启用'}</Button></div></Modal>}</PopupPresence>
  </div>;
}
function ArrowRightIcon() { return <ArrowUpRight size={14}/>; }
